// packages/svelte/src/lib/components/tooltip/tooltip-root.svelte
<script module lang="ts">
  import type { Snippet } from 'svelte'
  import type { UsePresenceProps } from '../presence'
  import type { UseTooltipProps } from './use-tooltip.svelte'

  export interface TooltipRootBaseProps extends UseTooltipProps, UsePresenceProps {}
  export interface TooltipRootProps extends TooltipRootBaseProps {
    children?: Snippet
  }
</script>

<script lang="ts">
  import { PresenceProvider, usePresence } from '../presence'
  import { splitPresenceProps } from '../presence/split-presence-props.svelte'
  import { TooltipProvider } from './use-tooltip-context'
  import { useTooltip } from './use-tooltip.svelte'

  let { open = $bindable(), ...props }: TooltipRootProps = $props()
  const providedId = $props.id()

  const [presenceProps, localProps] = $derived(splitPresenceProps(props))
  const { children, ...useTooltipProps } = $derived(localProps)

  const resolvedProps = $derived<UseTooltipProps>({
    ...useTooltipProps,
    id: providedId,
    onOpenChange(details) {
      useTooltipProps.onOpenChange?.(details)
      open = details.open
    },
  })

  const tooltip = useTooltip(() => resolvedProps)
  const presence = usePresence(() => ({ ...presenceProps, present: tooltip().open }))

  TooltipProvider(tooltip)
  PresenceProvider(presence)
</script>

{@render children?.()}

// packages/react/src/components/tooltip/tooltip-root.tsx
import { mergeProps } from '@zag-js/react'
import type { ReactNode } from 'react'
import type { UsePresenceProps } from '../presence'
import { PresenceProvider, usePresence } from '../presence'
import { splitPresenceProps } from '../presence/split-presence-props'
import { type UseTooltipProps, useTooltip } from './use-tooltip'
import { TooltipProvider } from './use-tooltip-context'

export interface TooltipRootBaseProps extends UseTooltipProps, UsePresenceProps {}
export interface TooltipRootProps extends TooltipRootBaseProps {
  children?: ReactNode
}

export const TooltipRoot = (props: TooltipRootProps) => {
  const [presenceProps, { children, ...localProps }] = splitPresenceProps(props)
  const tooltip = useTooltip(localProps)
  const presence = usePresence(mergeProps({ present: tooltip.open }, presenceProps))

  return (
    <TooltipProvider value={tooltip}>
      <PresenceProvider value={presence}>{children}</PresenceProvider>
    </TooltipProvider>
  )
}
