// packages/solid/src/tooltip/tooltip-arrow-tip.tsx
import { ark, type HTMLArkProps } from '../factory'
import { useTooltipContext } from './tooltip-context'

export type TooltipArrowTipProps = HTMLArkProps<'div'>

export const TooltipArrowTip = (props: TooltipArrowTipProps) => {
  const tooltip = useTooltipContext()

  return <ark.div {...tooltip().arrowTipProps} {...props} />
}

// packages/frameworks/vue/src/tooltip/tooltip-arrow-tip.tsx
import { defineComponent } from 'vue'
import { ark, type HTMLArkProps } from '../factory'
import { useTooltipContext } from './tooltip-context'

export interface TooltipArrowTipProps extends HTMLArkProps<'div'> {}

export const TooltipArrowTip = defineComponent<TooltipArrowTipProps>(
  (_, { slots, attrs }) => {
    const api = useTooltipContext()

    return () => (
      <ark.div {...api.value.arrowTipProps} {...attrs}>
        {slots.default?.()}
      </ark.div>
    )
  },
  {
    name: 'TooltipArrowTip',
  },
)
