// docs/src/components/pin-input/pin-input.react.tsx
import { PinInput, PinInputField } from '@atlas/react'
import { useState } from 'react'

export const ReactPinInput = () => {
  const [disabled, setDisabled] = useState(true)
  return (
    <>
      <button onClick={() => setDisabled((value) => !value)}>Activate me</button>
      <PinInput disabled={disabled} placeholder="*" value={['1', '2', '3']}>
        {[0, 1, 2].map((id, index) => (
          <PinInputField key={id} index={index} />
        ))}
      </PinInput>
    </>
  )
}

// docs/src/components/pin-input/pin-input.solid.tsx
/** @jsxImportSource solid-js */
import { PinInput, PinInputField } from '@atlas/solid-js'
import { createSignal } from 'solid-js'

export const Basic = () => {
  const [disabled, setDisabled] = createSignal(true)
  return (
    <>
      <button onClick={() => setDisabled(false)}>activate</button>
      <PinInput
        placeholder="*"
        onComplete={(e) => alert(e.valueAsString)}
        disabled={disabled()}
        otp
      >
        {[0, 1, 2].map((id, index) => (
          <PinInputField index={index} />
        ))}
      </PinInput>
    </>
  )
}
