// packages/svelte/src/lib/components/accordion/accordion-item.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'
  import type { ItemProps } from '@zag-js/accordion'

  export interface AccordionItemBaseProps extends ItemProps, PolymorphicProps<'div'> {}
  export interface AccordionItemProps extends Assign<HTMLProps<'div'>, AccordionItemBaseProps> {}
</script>

<script lang="ts">
  import { createSplitProps } from '$lib/utils/create-split-props'
  import { useRenderStrategyPropsContext } from '$lib/utils/render-strategy'
  import { mergeProps } from '@zag-js/svelte'
  import { CollapsibleRoot } from '../collapsible'
  import { useAccordionContext } from './use-accordion-context'
  import { AccordionItemProvider } from './use-accordion-item-context'
  import { AccordionItemPropsProvider } from './use-accordion-item-props-context'

  const props: AccordionItemProps = $props()
  const [itemProps, localProps] = $derived(createSplitProps<ItemProps>()(props, ['value', 'disabled']))

  const accordion = useAccordionContext()
  const renderStrategy = useRenderStrategyPropsContext()

  const itemState = $derived(accordion().getItemState(itemProps))
  const mergedProps = $derived(mergeProps(accordion().getItemProps(itemProps), localProps))

  const itemContentProps = $derived(accordion().getItemContentProps(itemProps))

  AccordionItemPropsProvider(() => itemProps)
  AccordionItemProvider(() => itemState)
</script>

<CollapsibleRoot
  open={itemState.expanded}
  ids={{ content: itemContentProps.id ?? undefined }}
  {...renderStrategy()}
  {...mergedProps}
/>

// packages/react/src/components/accordion/accordion-item.tsx
'use client'

import type { ItemProps } from '@zag-js/accordion'
import { mergeProps } from '@zag-js/react'
import { Collapsible } from '../../components'
import { createSplitProps } from '../../utils/create-split-props'
import { useRenderStrategyPropsContext } from '../../utils/render-strategy'
import type { HTMLProps, PolymorphicProps } from '../factory'
import { useAccordionContext } from './use-accordion-context'
import { AccordionItemProvider } from './use-accordion-item-context'
import { AccordionItemPropsProvider } from './use-accordion-item-props-context'

export interface AccordionItemBaseProps extends ItemProps, PolymorphicProps {}
export interface AccordionItemProps extends HTMLProps<'div'>, AccordionItemBaseProps {}

const splitItemProps = createSplitProps<ItemProps>()

export const AccordionItem = ({ ref, ...props }: AccordionItemProps) => {
  const [itemProps, localProps] = splitItemProps(props, ['value', 'disabled'])
  const accordion = useAccordionContext()
  const renderStrategy = useRenderStrategyPropsContext()
  const mergedProps = mergeProps(accordion.getItemProps(itemProps), localProps)
  const item = accordion.getItemState(itemProps)
  const itemContentProps = accordion.getItemContentProps(itemProps)

  return (
    <AccordionItemPropsProvider value={itemProps}>
      <AccordionItemProvider value={item}>
        <Collapsible.Root
          ref={ref}
          open={item.expanded}
          ids={{ content: itemContentProps.id }}
          {...renderStrategy}
          {...mergedProps}
        />
      </AccordionItemProvider>
    </AccordionItemPropsProvider>
  )
}

AccordionItem.displayName = 'AccordionItem'
