// frameworks/solid/src/accordion/accordion-item-context.tsx
import type { JSX } from 'solid-js'
import { useAccordionItemContext, type UseAccordionItemContext } from './use-accordion-item-context'

export interface AccordionItemContextProps {
  children: (context: UseAccordionItemContext) => JSX.Element
}

export const AccordionItemContext = (props: AccordionItemContextProps) =>
  props.children(useAccordionItemContext())

// packages/react/src/components/accordion/accordion-item-context.tsx
import type { ReactNode } from 'react'
import { type UseAccordionItemContext, useAccordionItemContext } from './use-accordion-item-context'

export interface AccordionItemContextProps {
  children: (context: UseAccordionItemContext) => ReactNode
}

export const AccordionItemContext = (props: AccordionItemContextProps) => props.children(useAccordionItemContext())
