// frameworks/vue/src/components/radio-group/radio-group-item-control.tsx
import { defineComponent } from 'vue'
import { type HTMLArkProps, ark } from '../factory'
import { useRadioGroupContext } from './use-radio-group-context'
import { useRadioGroupItemPropsContext } from './use-radio-group-item-props-context'

export interface RadioGroupItemControlProps extends HTMLArkProps<'div'> {}

export const RadioGroupItemControl = defineComponent<RadioGroupItemControlProps>(
  (_, { slots, attrs }) => {
    const api = useRadioGroupContext()
    const itemProps = useRadioGroupItemPropsContext()

    return () => (
      <>
        <ark.div {...api.value.getItemControlProps(itemProps)} {...attrs}>
          {slots.default?.()}
        </ark.div>
        <input {...api.value.getItemHiddenInputProps(itemProps)} />
      </>
    )
  },
  {
    name: 'RadioGroupItemControl',
  },
)

// frameworks/solid/src/radio-group/radio-group-item-control.tsx
import { mergeProps } from '@zag-js/solid'
import { ark, type HTMLArkProps } from '../factory'
import { useRadioGroupContext } from './use-radio-group-context'
import { useRadioGroupItemPropsContext } from './use-radio-group-item-context'

export interface RadioGroupItemControlProps extends HTMLArkProps<'div'> {}

export const RadioGroupItemControl = (props: RadioGroupItemControlProps) => {
  const api = useRadioGroupContext()
  const itemProps = useRadioGroupItemPropsContext()
  const mergedProps = mergeProps(() => api().getItemControlProps(itemProps), props)

  return (
    <>
      <ark.div {...mergedProps} />
      <input {...api().getItemHiddenInputProps(itemProps)} />
    </>
  )
}
