// packages/react/src/components/tree-view/tree-view-node-checkbox-indicator.tsx
import type { HTMLProps } from '../factory'
import { useTreeViewNodeContext } from './use-tree-view-node-context'

export interface TreeViewNodeCheckboxIndicatorBaseProps {
  children?: React.ReactNode | undefined
  indeterminate?: React.ReactNode | undefined
  fallback?: React.ReactNode | undefined
}
export interface TreeViewNodeCheckboxIndicatorProps extends HTMLProps<'span'>, TreeViewNodeCheckboxIndicatorBaseProps {}

export const TreeViewNodeCheckboxIndicator = (props: TreeViewNodeCheckboxIndicatorProps) => {
  const { children, indeterminate, fallback } = props
  const nodeState = useTreeViewNodeContext()
  const checkedState = nodeState.checked

  if (checkedState === 'indeterminate' && indeterminate) {
    return <>{indeterminate}</>
  }

  if (checkedState === true && children) {
    return <>{children}</>
  }

  return <>{fallback}</>
}

TreeViewNodeCheckboxIndicator.displayName = 'TreeViewNodeCheckboxIndicator'

// packages/solid/src/components/tree-view/tree-view-node-checkbox-indicator.tsx
import { type JSX, createMemo } from 'solid-js'
import { useTreeViewNodeContext } from './use-tree-view-node-context'

export interface TreeViewNodeCheckboxIndicatorBaseProps {
  children?: JSX.Element
  indeterminate?: JSX.Element
  fallback?: JSX.Element
}
export interface TreeViewNodeCheckboxIndicatorProps extends TreeViewNodeCheckboxIndicatorBaseProps {}

export const TreeViewNodeCheckboxIndicator = (props: TreeViewNodeCheckboxIndicatorProps) => {
  const nodeState = useTreeViewNodeContext()

  const checkedState = createMemo(() => nodeState().checked)

  if (checkedState() === 'indeterminate' && props.indeterminate) {
    return props.indeterminate
  }

  if (checkedState() === true && props.children) {
    return props.children
  }

  return props.fallback
}
