// packages/svelte/src/lib/components/cascade-select/cascade-select-hidden-input.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface CascadeSelectHiddenInputBaseProps extends PolymorphicProps<'input'>, RefAttribute {}
  export interface CascadeSelectHiddenInputProps extends Assign<
    HTMLProps<'input'>,
    CascadeSelectHiddenInputBaseProps
  > {}
</script>

<script lang="ts">
  import { Ark } from '$lib/components/factory'
  import { mergeProps } from '@zag-js/svelte'
  import { useCascadeSelectContext } from './use-cascade-select-context'

  let { ref = $bindable(null), ...props }: CascadeSelectHiddenInputProps = $props()
  const cascadeSelect = useCascadeSelectContext()
  const mergedProps = $derived(mergeProps(cascadeSelect().getHiddenInputProps(), props))
</script>

<Ark as="input" bind:ref {...mergedProps} />

// packages/react/src/components/cascade-select/cascade-select-hidden-input.tsx
import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory'
import { useCascadeSelectContext } from './use-cascade-select-context'

export interface CascadeSelectHiddenInputBaseProps extends PolymorphicProps {}
export interface CascadeSelectHiddenInputProps extends HTMLProps<'input'>, CascadeSelectHiddenInputBaseProps {}

export const CascadeSelectHiddenInput = forwardRef<HTMLInputElement, CascadeSelectHiddenInputProps>((props, ref) => {
  const cascadeSelect = useCascadeSelectContext()
  const mergedProps = mergeProps(cascadeSelect.getHiddenInputProps(), props)

  return <ark.input {...mergedProps} ref={ref} />
})

CascadeSelectHiddenInput.displayName = 'CascadeSelectHiddenInput'
