// packages/vue/src/components/cascade-select/cascade-select-clear-trigger.vue
<script lang="ts">
import type { ButtonHTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory'

export interface CascadeSelectClearTriggerBaseProps extends PolymorphicProps {}
export interface CascadeSelectClearTriggerProps
  extends
    CascadeSelectClearTriggerBaseProps,
    /**
     * @vue-ignore
     */
    ButtonHTMLAttributes {}
</script>

<script setup lang="ts">
import { useForwardExpose } from '../../utils/use-forward-expose'
import { ark } from '../factory'
import { useCascadeSelectContext } from './use-cascade-select-context'

defineProps<CascadeSelectClearTriggerProps>()
const cascadeSelect = useCascadeSelectContext()

useForwardExpose()
</script>

<template>
  <ark.button v-bind="cascadeSelect.getClearTriggerProps()" :as-child="asChild">
    <slot />
  </ark.button>
</template>

// packages/react/src/components/cascade-select/cascade-select-clear-trigger.tsx
import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory'
import { useCascadeSelectContext } from './use-cascade-select-context'

export interface CascadeSelectClearTriggerBaseProps extends PolymorphicProps {}
export interface CascadeSelectClearTriggerProps extends HTMLProps<'button'>, CascadeSelectClearTriggerBaseProps {}

export const CascadeSelectClearTrigger = forwardRef<HTMLButtonElement, CascadeSelectClearTriggerProps>((props, ref) => {
  const cascadeSelect = useCascadeSelectContext()
  const mergedProps = mergeProps(cascadeSelect.getClearTriggerProps(), props)

  return <ark.button {...mergedProps} ref={ref} />
})

CascadeSelectClearTrigger.displayName = 'CascadeSelectClearTrigger'
