// packages/svelte/src/lib/components/cascade-select/cascade-select-context.svelte
<script module lang="ts">
  import type { Snippet } from 'svelte'
  import type { UseCascadeSelectReturn } from './use-cascade-select.svelte'

  export interface CascadeSelectContextProps {
    render: Snippet<[UseCascadeSelectReturn]>
  }
</script>

<script lang="ts">
  import { useCascadeSelectContext } from './use-cascade-select-context'

  const props: CascadeSelectContextProps = $props()
  const cascadeSelect = useCascadeSelectContext()
</script>

{@render props.render(cascadeSelect)}

// packages/react/src/components/cascade-select/cascade-select-context.tsx
import type { ReactNode } from 'react'
import { type UseCascadeSelectContext, useCascadeSelectContext } from './use-cascade-select-context'

export interface CascadeSelectContextProps {
  children: (context: UseCascadeSelectContext) => ReactNode
}

export const CascadeSelectContext = (props: CascadeSelectContextProps) => props.children(useCascadeSelectContext())
