// packages/svelte/src/lib/components/cascade-select/cascade-select-item-indicator.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface CascadeSelectItemIndicatorBaseProps extends PolymorphicProps<'div'>, RefAttribute {}
  export interface CascadeSelectItemIndicatorProps
    extends Assign<HTMLProps<'div'>, CascadeSelectItemIndicatorBaseProps> {}
</script>

<script lang="ts">
  import { Ark } from '$lib/components/factory'
  import { mergeProps } from '@zag-js/svelte'
  import { useCascadeSelectContext } from './use-cascade-select-context'
  import { useCascadeSelectItemPropsContext } from './use-cascade-select-item-props-context'

  let { ref = $bindable(null), ...props }: CascadeSelectItemIndicatorProps = $props()
  const cascadeSelect = useCascadeSelectContext()
  const itemProps = useCascadeSelectItemPropsContext()
  const mergedProps = $derived(mergeProps(cascadeSelect().getItemIndicatorProps(itemProps()), props))
</script>

<Ark as="div" bind:ref {...mergedProps} />

// packages/react/src/components/cascade-select/cascade-select-item-indicator.tsx
import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory'
import { useCascadeSelectContext } from './use-cascade-select-context'
import { useCascadeSelectItemPropsContext } from './use-cascade-select-item-props-context'

export interface CascadeSelectItemIndicatorBaseProps extends PolymorphicProps {}
export interface CascadeSelectItemIndicatorProps extends HTMLProps<'div'>, CascadeSelectItemIndicatorBaseProps {}

export const CascadeSelectItemIndicator = forwardRef<HTMLDivElement, CascadeSelectItemIndicatorProps>((props, ref) => {
  const cascadeSelect = useCascadeSelectContext()
  const itemProps = useCascadeSelectItemPropsContext()
  const mergedProps = mergeProps(cascadeSelect.getItemIndicatorProps(itemProps), props)

  return <ark.div {...mergedProps} ref={ref} />
})

CascadeSelectItemIndicator.displayName = 'CascadeSelectItemIndicator'
