// frameworks/solid/src/combobox/use-combobox-item-context.ts
import type { ItemProps, ItemState } from '@zag-js/combobox'
import type { Accessor } from 'solid-js'
import { createContext } from '../create-context'

export interface UseComboboxItemContext extends Accessor<ItemState> {}

export const [ComboboxItemProvider, useComboboxItemContext] = createContext<UseComboboxItemContext>(
  {
    hookName: 'useComboboxItemContext',
    providerName: '<ComboboxItemProvider />',
  },
)
export const [ComboboxItemPropsProvider, useComboboxItemPropsContext] = createContext<ItemProps>({
  hookName: 'useComboboxItemPropsContext',
  providerName: '<ComboboxItemPropsProvider />',
})

// packages/react/src/components/combobox/use-combobox-item-context.ts
'use client'

import type { ItemState } from '@zag-js/combobox'
import { createContext } from '../../utils/create-context.ts'

export interface UseComboboxItemContext extends ItemState {}

export const [ComboboxItemProvider, useComboboxItemContext] = createContext<UseComboboxItemContext>({
  name: 'ComboboxItemContext',
  hookName: 'useComboboxItemContext',
  providerName: '<ComboboxItemProvider />',
})
