// packages/react/src/components/avatar/avatar-context.tsx
import type { ReactNode } from 'react'
import { type UseAvatarContext, useAvatarContext } from './use-avatar-context'

export interface AvatarContextProps {
  children: (context: UseAvatarContext) => ReactNode
}

export const AvatarContext = (props: AvatarContextProps) => props.children(useAvatarContext())

// frameworks/solid/src/components/avatar/avatar-context.tsx
import type { JSX } from 'solid-js'
import { type UseAvatarContext, useAvatarContext } from './use-avatar-context'

export interface AvatarContextProps {
  children: (context: UseAvatarContext) => JSX.Element
}

export const AvatarContext = (props: AvatarContextProps) => props.children(useAvatarContext())
