// packages/react/src/components/meter/meter-context.tsx
'use client'

import type { ReactNode } from 'react'
import { type UseMeterContext, useMeterContext } from './use-meter-context.ts'

export interface MeterContextProps {
  children: (context: UseMeterContext) => ReactNode
}

export const MeterContext = (props: MeterContextProps) => props.children(useMeterContext())

// packages/solid/src/components/meter/meter-context.tsx
import type { JSX } from 'solid-js'
import { type UseMeterContext, useMeterContext } from './use-meter-context.ts'

export interface MeterContextProps {
  children: (context: UseMeterContext) => JSX.Element
}

export const MeterContext = (props: MeterContextProps) => props.children(useMeterContext())
