// packages/vue/src/switch/switch.tsx
/* eslint-disable vue/no-reserved-component-names */
import { defineComponent, type PropType } from 'vue'
import { ark, type HTMLArkProps } from '../factory'
import type { Assign } from '../types'
import { createVueProps } from '../utils'
import { SwitchProvider } from './switch-context'
import { useSwitch, type UseSwitchProps } from './use-switch'

export type SwitchProps = Assign<HTMLArkProps<'label'>, UseSwitchProps>

const VueProps = createVueProps<SwitchProps>({
  checked: {
    type: Boolean as PropType<SwitchProps['checked']>,
  },
  dir: {
    type: String as PropType<SwitchProps['dir']>,
  },
  disabled: {
    type: Boolean as PropType<SwitchProps['disabled']>,
  },
  focusable: {
    type: Boolean as PropType<SwitchProps['focusable']>,
  },
  form: {
    type: String as PropType<SwitchProps['form']>,
  },
  getRootNode: {
    type: Function as PropType<SwitchProps['getRootNode']>,
  },
  id: {
    type: String as PropType<SwitchProps['id']>,
  },
  ids: {
    type: Object as PropType<SwitchProps['ids']>,
  },
  invalid: {
    type: Boolean as PropType<SwitchProps['invalid']>,
  },
  label: {
    type: String as PropType<SwitchProps['label']>,
  },
  modelValue: {
    type: Boolean as PropType<SwitchProps['modelValue']>,
  },
  name: {
    type: String as PropType<SwitchProps['name']>,
  },
  readOnly: {
    type: Boolean as PropType<SwitchProps['readOnly']>,
  },
  required: {
    type: Boolean as PropType<SwitchProps['required']>,
  },
  value: {
    type: [String, Number] as PropType<SwitchProps['value']>,
  },
})

export const Switch = defineComponent({
  name: 'Switch',
  props: VueProps,
  emit: ['change', 'update:modelValue'],
  setup(props, { slots, attrs, emit }) {
    const api = useSwitch(emit, props)

    SwitchProvider(api)

    return () => (
      <ark.label {...api.value.rootProps} {...attrs}>
        {slots.default?.(api.value)}
      </ark.label>
    )
  },
})

// packages/solid/src/switch/switch.tsx
import { mergeProps } from '@zag-js/solid'
import type { JSX } from 'solid-js'
import { createSplitProps } from '../create-split-props'
import { ark, type HTMLArkProps } from '../factory'
import { runIfFn } from '../run-if-fn'
import type { Assign } from '../types'
import { SwitchProvider, type SwitchContext } from './switch-context'
import { useSwitch, type UseSwitchProps } from './use-switch'

export type SwitchProps = Assign<
  HTMLArkProps<'label'>,
  UseSwitchProps & {
    children?: JSX.Element | ((context: SwitchContext) => JSX.Element)
  }
>

export const Switch = (props: SwitchProps) => {
  const [switchProps, labelProps] = createSplitProps<UseSwitchProps>()(props, [
    'checked',
    'dir',
    'disabled',
    'focusable',
    'form',
    'getRootNode',
    'id',
    'ids',
    'invalid',
    'label',
    'name',
    'onChange',
    'readOnly',
    'required',
    'value',
  ])
  const api = useSwitch(switchProps)
  const rootProps = mergeProps(() => api().rootProps, labelProps)
  const getChildren = () => runIfFn(props.children, api)

  return (
    <SwitchProvider value={api}>
      <ark.label {...rootProps}>{getChildren()}</ark.label>
    </SwitchProvider>
  )
}
