// packages/solid/src/components/select/examples/dynamic-items.tsx
import { Select, createListCollection } from '@ark-ui/solid/select'
import { ChevronsUpDownIcon, XIcon } from 'lucide-solid'
import { createMemo, createSignal } from 'solid-js'
import { Index, Portal } from 'solid-js/web'
import button from 'styles/button.module.css'
import styles from 'styles/select.module.css'

export const DynamicItems = () => {
  const [items, setItems] = createSignal(['React', 'Solid', 'Vue', 'Svelte'])
  const collection = createMemo(() =>
    createListCollection({
      items: items(),
    }),
  )

  const addItem = () => setItems([...items(), 'Angular'])

  return (
    <div>
      <Select.Root class={styles.Root} collection={collection()}>
        <Select.Label class={styles.Label}>Framework</Select.Label>
        <Select.Control class={styles.Control}>
          <Select.Trigger class={styles.Trigger}>
            <Select.ValueText class={styles.ValueText} placeholder="Select a Framework" />
          </Select.Trigger>
          <div class={styles.Indicators}>
            <Select.ClearTrigger class={styles.ClearTrigger}>
              <XIcon />
            </Select.ClearTrigger>
            <Select.Indicator class={styles.Indicator}>
              <ChevronsUpDownIcon />
            </Select.Indicator>
          </div>
        </Select.Control>
        <Portal>
          <Select.Positioner>
            <Select.Content class={styles.Content}>
              <Select.List class={styles.List}>
                <Select.ItemGroup class={styles.ItemGroup}>
                  <Select.ItemGroupLabel class={styles.ItemGroupLabel}>Frameworks</Select.ItemGroupLabel>
                  <Index each={collection().items}>
                    {(item) => (
                      <Select.Item class={styles.Item} item={item()}>
                        <Select.ItemText class={styles.ItemText}>{item()}</Select.ItemText>
                        <Select.ItemIndicator class={styles.ItemIndicator}>✓</Select.ItemIndicator>
                      </Select.Item>
                    )}
                  </Index>
                </Select.ItemGroup>
              </Select.List>
            </Select.Content>
          </Select.Positioner>
        </Portal>
        <Select.HiddenSelect />
      </Select.Root>

      <button class={button.Root} style={{ 'margin-top': '1rem' }} type="button" onClick={addItem}>
        Add Item
      </button>
    </div>
  )
}

// packages/react/src/components/select/examples/dynamic-items.tsx
import { Portal } from '@ark-ui/react/portal'
import { Select, createListCollection } from '@ark-ui/react/select'
import { ChevronsUpDownIcon, XIcon } from 'lucide-react'
import { useState } from 'react'
import button from 'styles/button.module.css'
import styles from 'styles/select.module.css'

export const DynamicItems = () => {
  const [items, setItems] = useState(['React', 'Solid', 'Vue', 'Svelte'])
  const collection = createListCollection({
    items: items,
  })

  const addItem = () => setItems([...items, 'Angular'])

  return (
    <div>
      <Select.Root className={styles.Root} collection={collection}>
        <Select.Label className={styles.Label}>Framework</Select.Label>
        <Select.Control className={styles.Control}>
          <Select.Trigger className={styles.Trigger}>
            <Select.ValueText className={styles.ValueText} placeholder="Select a Framework" />
          </Select.Trigger>
          <div className={styles.Indicators}>
            <Select.ClearTrigger className={styles.ClearTrigger}>
              <XIcon />
            </Select.ClearTrigger>
            <Select.Indicator className={styles.Indicator}>
              <ChevronsUpDownIcon />
            </Select.Indicator>
          </div>
        </Select.Control>
        <Portal>
          <Select.Positioner>
            <Select.Content className={styles.Content}>
              <Select.List className={styles.List}>
                <Select.ItemGroup className={styles.ItemGroup}>
                  <Select.ItemGroupLabel className={styles.ItemGroupLabel}>Frameworks</Select.ItemGroupLabel>
                  {collection.items.map((item) => (
                    <Select.Item className={styles.Item} key={item} item={item}>
                      <Select.ItemText className={styles.ItemText}>{item}</Select.ItemText>
                      <Select.ItemIndicator className={styles.ItemIndicator}>✓</Select.ItemIndicator>
                    </Select.Item>
                  ))}
                </Select.ItemGroup>
              </Select.List>
            </Select.Content>
          </Select.Positioner>
        </Portal>
        <Select.HiddenSelect />
      </Select.Root>

      <button className={button.Root} style={{ marginTop: '1rem' }} type="button" onClick={addItem}>
        Add Item
      </button>
    </div>
  )
}
