// frameworks/solid/src/radio-group/radio-group-item-context.tsx
import type { JSX } from 'solid-js'
import {
  useRadioGroupItemContext,
  type UseRadioGroupItemContext,
} from './use-radio-group-item-context'

export interface RadioGroupItemContextProps {
  children: (context: UseRadioGroupItemContext) => JSX.Element
}

export const RadioGroupItemContext = (props: RadioGroupItemContextProps) =>
  props.children(useRadioGroupItemContext())

// packages/react/src/components/radio-group/radio-group-item-context.tsx
import type { ReactNode } from 'react'
import { type UseRadioGroupItemContext, useRadioGroupItemContext } from './use-radio-group-item-context'

export interface RadioGroupItemContextProps {
  children: (context: UseRadioGroupItemContext) => ReactNode
}

export const RadioGroupItemContext = (props: RadioGroupItemContextProps) => props.children(useRadioGroupItemContext())
