// packages/svelte/src/lib/components/number-input/number-input-increment-trigger.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'

  export interface NumberInputIncrementTriggerBaseProps extends PolymorphicProps<'button'> {}
  export interface NumberInputIncrementTriggerProps
    extends Assign<HTMLProps<'button'>, NumberInputIncrementTriggerBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Ark } from '../factory'
  import { useNumberInputContext } from './use-number-input-context'

  const props: NumberInputIncrementTriggerProps = $props()

  const numberInput = useNumberInputContext()
  const mergedProps = $derived(mergeProps(numberInput().getIncrementTriggerProps(), props))
</script>

<Ark as="button" {...mergedProps} />

// packages/react/src/components/number-input/number-input-increment-trigger.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory'
import { useNumberInputContext } from './use-number-input-context'

export interface NumberInputIncrementTriggerBaseProps extends PolymorphicProps {}
export interface NumberInputIncrementTriggerProps extends HTMLProps<'button'>, NumberInputIncrementTriggerBaseProps {}

export const NumberInputIncrementTrigger = ({ ref, ...props }: NumberInputIncrementTriggerProps) => {
  const numberInput = useNumberInputContext()
  const mergedProps = mergeProps(numberInput.getIncrementTriggerProps(), props)

  return <ark.button {...mergedProps} ref={ref} />
}

NumberInputIncrementTrigger.displayName = 'NumberInputIncrementTrigger'
