// packages/solid/src/slider/slider-control.tsx
import { ark, type HTMLArkProps } from '../factory'
import { useSliderContext } from './slider-context'

export type SliderControlProps = HTMLArkProps<'div'>

export const SliderControl = (props: SliderControlProps) => {
  const slider = useSliderContext()

  return <ark.div {...slider().controlProps} {...props} />
}

// frameworks/vue/src/components/slider/slider-control.tsx
import { defineComponent } from 'vue'
import { type HTMLArkProps, ark } from '../../factory'
import { useSliderContext } from './slider-context'

export interface SliderControlProps extends HTMLArkProps<'div'> {}

export const SliderControl = defineComponent<SliderControlProps>(
  (_, { slots, attrs }) => {
    const api = useSliderContext()

    return () => (
      <ark.div {...api.value.controlProps} {...attrs}>
        {slots.default?.()}
      </ark.div>
    )
  },
  {
    name: 'SliderControl',
  },
)
