// packages/vue/src/components/listbox/listbox-item-group-label.vue
<script lang="ts">
import type { HTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory'

export interface ListboxItemGroupLabelBaseProps extends PolymorphicProps {}
export interface ListboxItemGroupLabelProps
  extends ListboxItemGroupLabelBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
</script>

<script setup lang="ts">
import { ark } from '../factory'
import { useListboxContext } from './use-listbox-context'
import { useListboxItemGroupPropsContext } from './use-listbox-item-group-props-context'
import { useForwardExpose } from '../../utils'

defineProps<ListboxItemGroupLabelProps>()
const listbox = useListboxContext()
const itemGroupProps = useListboxItemGroupPropsContext()
useForwardExpose()
</script>

<template>
  <ark.div v-bind="listbox.getItemGroupLabelProps({ htmlFor: itemGroupProps.id })" :as-child="asChild">
    <slot />
  </ark.div>
</template>

// packages/solid/src/components/listbox/listbox-item-group-label.tsx
import { mergeProps } from '@zag-js/solid'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory'
import { useListboxContext } from './use-listbox-context'
import { useListboxItemGroupPropsContext } from './use-listbox-item-group-props-context'

export interface ListboxItemGroupLabelBaseProps extends PolymorphicProps<'div'> {}
export interface ListboxItemGroupLabelProps extends HTMLProps<'div'>, ListboxItemGroupLabelBaseProps {}

export const ListboxItemGroupLabel = (props: ListboxItemGroupLabelProps) => {
  const listbox = useListboxContext()
  const itemGroupProps = useListboxItemGroupPropsContext()
  const mergedProps = mergeProps(() => listbox().getItemGroupLabelProps({ htmlFor: itemGroupProps.id }), props)

  return <ark.div {...mergedProps} />
}
