// packages/react/src/components/highlight/examples/ignore-case.tsx
import { Highlight } from '@ark-ui/react/highlight'
import styles from 'styles/highlight.module.css'

export const IgnoreCase = () => (
  <p className={styles.Text}>
    <Highlight
      className={styles.Mark}
      text="TypeScript provides static type checking. Using typescript helps catch errors early in development."
      query="typescript"
      ignoreCase
    />
  </p>
)

// packages/svelte/src/lib/components/highlight/examples/ignore-case.svelte
<script lang="ts">
  import { Highlight } from '@ark-ui/svelte/highlight'
  import styles from 'styles/highlight.module.css'
</script>

<p class={styles.Text}>
  <Highlight
    class={styles.Mark}
    text="TypeScript provides static type checking. Using typescript helps catch errors early in development."
    query="typescript"
    ignoreCase
  />
</p>
