// packages/vue/src/components/popover/examples/nested.vue
<script setup lang="ts">
import { Popover } from '@ark-ui/vue/popover'
import { Teleport } from 'vue'
import button from 'styles/button.module.css'
import styles from 'styles/popover.module.css'
</script>

<template>
  <Popover.Root lazyMount unmountOnExit>
    <Popover.Trigger :class="button.Root">Click Me</Popover.Trigger>
    <Teleport to="body">
      <Popover.Positioner :class="styles.Positioner">
        <Popover.Content :class="styles.Content">
          <Popover.Title :class="styles.Title">Settings</Popover.Title>
          <Popover.Description :class="styles.Description">
            Manage your preferences and account settings.
          </Popover.Description>
          <Popover.Root lazyMount unmountOnExit :positioning="{ placement: 'right' }">
            <Popover.Trigger :class="button.Root">Advanced</Popover.Trigger>
            <Teleport to="body">
              <Popover.Positioner :class="styles.Positioner">
                <Popover.Content :class="styles.Content">
                  <Popover.Title :class="styles.Title">Advanced Settings</Popover.Title>
                  <Popover.Description :class="styles.Description">
                    Configure advanced options for power users.
                  </Popover.Description>
                </Popover.Content>
              </Popover.Positioner>
            </Teleport>
          </Popover.Root>
        </Popover.Content>
      </Popover.Positioner>
    </Teleport>
  </Popover.Root>
</template>

// packages/svelte/src/lib/components/popover/examples/nested.svelte
<script lang="ts">
  import { Popover } from '@ark-ui/svelte/popover'
  import { Portal } from '@ark-ui/svelte/portal'
  import button from 'styles/button.module.css'
  import styles from 'styles/popover.module.css'
</script>

<Popover.Root lazyMount unmountOnExit>
  <Popover.Trigger class={button.Root}>Click Me</Popover.Trigger>
  <Portal>
    <Popover.Positioner class={styles.Positioner}>
      <Popover.Content class={styles.Content}>
        <Popover.Title class={styles.Title}>Settings</Popover.Title>
        <Popover.Description class={styles.Description}>
          Manage your preferences and account settings.
        </Popover.Description>
        <Popover.Root lazyMount unmountOnExit positioning={{ placement: 'right' }}>
          <Popover.Trigger class={button.Root}>Advanced</Popover.Trigger>
          <Portal>
            <Popover.Positioner class={styles.Positioner}>
              <Popover.Content class={styles.Content}>
                <Popover.Title class={styles.Title}>Advanced Settings</Popover.Title>
                <Popover.Description class={styles.Description}>
                  Configure advanced options for power users.
                </Popover.Description>
              </Popover.Content>
            </Popover.Positioner>
          </Portal>
        </Popover.Root>
      </Popover.Content>
    </Popover.Positioner>
  </Portal>
</Popover.Root>
