// packages/frameworks/react/src/progress/progress-circle-range.tsx
import { mergeProps } from '@zag-js/react'
import { ark, type HTMLArkProps } from '../factory'
import { useProgressContext } from './progress-context'

export interface ProgressCircleRangeProps extends HTMLArkProps<'circle'> {}

export const ProgressCircleRange = (props: ProgressCircleRangeProps) => {
  const api = useProgressContext()
  const mergedProps = mergeProps(api.circleRangeProps, props)

  return <ark.circle {...mergedProps} />
}

ProgressCircleRange.displayName = 'ProgressCircleRange'

// packages/frameworks/vue/src/progress/progress-circle-range.tsx
import { defineComponent } from 'vue'
import { ark, type HTMLArkProps } from '../factory'
import { useProgressContext } from './progress-context'

export interface ProgressCircleRangeProps extends HTMLArkProps<'circle'> {}

export const ProgressCircleRange = defineComponent<ProgressCircleRangeProps>(
  (_, { attrs }) => {
    const api = useProgressContext()

    const style = {
      style: {
        cx: '50px',
        cy: '50px',
        r: '42px',
      },
    }

    return () => <ark.circle {...api.value.circleRangeProps} {...attrs} {...style} />
  },
  {
    name: 'ProgressCircleRange',
  },
)
