// packages/svelte/src/lib/components/editable/editable-root.svelte
<script module lang="ts">
  import type { Assign, HTMLProps } from '$lib/types'
  import type { UseEditableProps } from './use-editable.svelte'

  export interface EditableRootBaseProps extends UseEditableProps {}
  export interface EditableRootProps extends Assign<HTMLProps<'div'>, EditableRootBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Ark } from '../factory'
  import { splitEditableProps } from './split-editable-props'
  import { EditableProvider } from './use-editable-context'
  import { useEditable } from './use-editable.svelte'

  let { value = $bindable(), ...props }: EditableRootProps = $props()

  const providedId = $props.id()

  const [useEditableProps, localProps] = splitEditableProps(props)

  const machineProps = $derived.by<UseEditableProps>(() => {
    return {
      ...useEditableProps,
      id: useEditableProps.id ?? providedId,
      value,
      onValueChange(details) {
        useEditableProps.onValueChange?.(details)
        value = details.value
      },
    }
  })

  const editable = useEditable(() => machineProps)
  const mergedProps = $derived(mergeProps(editable().getRootProps(), localProps))

  EditableProvider(editable)
</script>

<Ark as="div" {...mergedProps} />

// packages/react/src/components/editable/editable-root.tsx
import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import type { Assign } from '../../types'
import { createSplitProps } from '../../utils/create-split-props'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory'
import { type UseEditableProps, useEditable } from './use-editable'
import { EditableProvider } from './use-editable-context'

export interface EditableRootBaseProps extends UseEditableProps, PolymorphicProps {}
export interface EditableRootProps extends Assign<HTMLProps<'div'>, EditableRootBaseProps> {}

export const EditableRoot = forwardRef<HTMLDivElement, EditableRootProps>((props, ref) => {
  const [useEditableProps, localProps] = createSplitProps<UseEditableProps>()(props, [
    'activationMode',
    'autoResize',
    'defaultValue',
    'disabled',
    'finalFocusEl',
    'form',
    'id',
    'ids',
    'invalid',
    'maxLength',
    'name',
    'onEdit',
    'onFocusOutside',
    'onInteractOutside',
    'onPointerDownOutside',
    'onValueChange',
    'onValueCommit',
    'onValueRevert',
    'placeholder',
    'readOnly',
    'selectOnFocus',
    'startWithEditView',
    'submitMode',
    'translations',
    'value',
  ])
  const editable = useEditable(useEditableProps)
  const mergedProps = mergeProps(editable.getRootProps(), localProps)

  return (
    <EditableProvider value={editable}>
      <ark.div {...mergedProps} ref={ref} />
    </EditableProvider>
  )
})

EditableRoot.displayName = 'EditableRoot'
