// packages/solid/src/dialog/dialog-backdrop.tsx
import { mergeProps } from '@zag-js/solid'
import { ark, type HTMLArkProps } from '../factory'
import { Presence, splitPresenceProps, type PresenceProps } from '../presence'
import { useDialogContext } from './dialog-context'

export type DialogBackdropProps = HTMLArkProps<'div'> & PresenceProps

export const DialogBackdrop = (props: DialogBackdropProps) => {
  const [presenceProps, localProps] = splitPresenceProps(props)
  const api = useDialogContext()
  const mergedProps = mergeProps(() => api().backdropProps, localProps)

  return (
    <Presence present={api().isOpen} {...presenceProps}>
      <ark.div {...mergedProps} />
    </Presence>
  )
}

// packages/frameworks/solid/src/dialog/dialog-backdrop.tsx
import { mergeProps } from '@zag-js/solid'
import { Show } from 'solid-js'
import { ark, type HTMLArkProps } from '../factory'
import { usePresence, usePresencePropsContext } from '../presence'
import { useDialogContext } from './dialog-context'

export interface DialogBackdropProps extends HTMLArkProps<'div'> {}

export const DialogBackdrop = (props: DialogBackdropProps) => {
  const api = useDialogContext()
  const presenceProps = usePresencePropsContext()
  const presenceApi = usePresence(mergeProps(presenceProps, () => ({ present: api().isOpen })))
  const mergedProps = mergeProps(
    () => api().backdropProps,
    () => presenceApi().presenceProps,
    props,
  )

  return (
    <Show when={!presenceApi().isUnmounted}>
      <ark.div {...mergedProps} />
    </Show>
  )
}
