// packages/svelte/src/lib/components/number-flow/number-flow-symbol.svelte
<script module lang="ts">
  import type { SymbolProps } from '@zag-js/number-flow'
  import type { HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface NumberFlowSymbolBaseProps extends SymbolProps, PolymorphicProps<'span'>, RefAttribute {}
  export interface NumberFlowSymbolProps extends HTMLProps<'span'>, NumberFlowSymbolBaseProps {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { createSplitProps } from '../../utils/create-split-props.ts'
  import { Ark } from '../factory/index.ts'
  import { useNumberFlowContext } from './use-number-flow-context.ts'

  let { ref = $bindable(null), children, ...props }: NumberFlowSymbolProps = $props()
  const [symbolProps, localProps] = $derived(createSplitProps<SymbolProps>()(props, ['segment']))

  const numberFlow = useNumberFlowContext()
  const mergedProps = $derived(mergeProps(numberFlow().getSymbolProps(symbolProps), localProps))
</script>

<Ark as="span" bind:ref {...mergedProps}>
  {#if children}
    {@render children()}
  {:else}
    {symbolProps.segment.value}
  {/if}
</Ark>

// packages/vue/src/components/number-flow/number-flow-symbol.vue
<script lang="ts">
import type { SymbolProps } from '@zag-js/number-flow'
import type { HTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory.ts'

export interface NumberFlowSymbolBaseProps extends SymbolProps, PolymorphicProps {}
export interface NumberFlowSymbolProps
  extends
    NumberFlowSymbolBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
</script>

<script setup lang="ts">
import { ark } from '../factory.ts'
import { useNumberFlowContext } from './use-number-flow-context.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

const props = defineProps<NumberFlowSymbolProps>()
const numberFlow = useNumberFlowContext()

useForwardExpose()
</script>

<template>
  <ark.span v-bind="numberFlow.getSymbolProps(props)" :as-child="asChild">
    <template v-if="$slots.render" #render="scope">
      <slot name="render" v-bind="scope" />
    </template>
    <template v-else #default>
      <slot>{{ props.segment.value }}</slot>
    </template>
  </ark.span>
</template>
