// packages/solid/src/components/pin-input/examples/verify-on-complete.tsx
import { PinInput } from '@ark-ui/solid/pin-input'
import { Index, createSignal } from 'solid-js'
import styles from 'styles/pin-input.module.css'

const expected = '1234'

export const VerifyOnComplete = () => {
  const [invalid, setInvalid] = createSignal(false)
  const [verified, setVerified] = createSignal(false)

  return (
    <div class="stack">
      <PinInput.Root
        class={styles.Root}
        count={4}
        otp
        invalid={invalid()}
        onValueChange={() => {
          setInvalid(false)
          setVerified(false)
        }}
        onValueComplete={(details) => {
          const matches = details.valueAsString === expected
          setInvalid(!matches)
          setVerified(matches)
        }}
      >
        <PinInput.Label class={styles.Label}>Enter {expected} to verify</PinInput.Label>
        <PinInput.Control class={styles.Control}>
          <Index each={[0, 1, 2, 3]}>{(id) => <PinInput.Input index={id()} class={styles.Input} />}</Index>
        </PinInput.Control>
        <PinInput.HiddenInput />
      </PinInput.Root>
      {invalid() && <p>Invalid code</p>}
      {verified() && <p>Code verified</p>}
    </div>
  )
}

// packages/svelte/src/lib/components/pin-input/examples/verify-on-complete.svelte
<script lang="ts">
  import { PinInput } from '@ark-ui/svelte/pin-input'
  import styles from 'styles/pin-input.module.css'

  const expected = '1234'
  let invalid = $state(false)
  let verified = $state(false)
</script>

<div class="stack">
  <PinInput.Root
    class={styles.Root}
    count={4}
    otp
    {invalid}
    onValueChange={() => {
      invalid = false
      verified = false
    }}
    onValueComplete={(details) => {
      const matches = details.valueAsString === expected
      invalid = !matches
      verified = matches
    }}
  >
    <PinInput.Label class={styles.Label}>Enter {expected} to verify</PinInput.Label>
    <PinInput.Control class={styles.Control}>
      {#each [0, 1, 2, 3] as id, index (id)}
        <PinInput.Input {index} class={styles.Input} />
      {/each}
    </PinInput.Control>
    <PinInput.HiddenInput />
  </PinInput.Root>
  {#if invalid}
    <p>Invalid code</p>
  {/if}
  {#if verified}
    <p>Code verified</p>
  {/if}
</div>
