// packages/vue/src/components/pin-input/examples/with-autofocus.vue
<script setup lang="ts">
import { PinInput } from '@ark-ui/vue/pin-input'
</script>

<template>
  <PinInput.Root :autoFocus="true">
    <PinInput.Label>PIN (auto-focused)</PinInput.Label>
    <PinInput.Control>
      <PinInput.Input v-for="id in [0, 1, 2, 3]" :key="id" :index="id" />
    </PinInput.Control>
    <PinInput.HiddenInput />
  </PinInput.Root>
</template>

// packages/svelte/src/lib/components/pin-input/examples/with-autofocus.svelte
<script lang="ts">
  import { PinInput } from '@ark-ui/svelte/pin-input'
</script>

<PinInput.Root autoFocus>
  <PinInput.Label>PIN (auto-focused)</PinInput.Label>
  <PinInput.Control>
    {#each [0, 1, 2, 3] as index}
      <PinInput.Input {index} />
    {/each}
  </PinInput.Control>
  <PinInput.HiddenInput />
</PinInput.Root>
