// packages/solid/src/components/collapsible/collapsible-indicator.tsx
import { mergeProps } from '@zag-js/solid'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory'
import { useCollapsibleContext } from './use-collapsible-context'

export interface CollapsibleIndicatorBaseProps extends PolymorphicProps<'div'> {}
export interface CollapsibleIndicatorProps extends HTMLProps<'div'>, CollapsibleIndicatorBaseProps {}

export const CollapsibleIndicator = (props: CollapsibleIndicatorProps) => {
  const collapsible = useCollapsibleContext()
  const mergedProps = mergeProps(() => collapsible().getIndicatorProps(), props)

  return <ark.div {...mergedProps} />
}

// packages/vue/src/components/collapsible/collapsible-indicator.vue
<script lang="ts">
import type { HTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory'

export interface CollapsibleIndicatorBaseProps extends PolymorphicProps {}
export interface CollapsibleIndicatorProps
  extends CollapsibleIndicatorBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
</script>

<script setup lang="ts">
import { ark } from '../factory'
import { useCollapsibleContext } from './use-collapsible-context'
import { useForwardExpose } from '../../utils'

defineProps<CollapsibleIndicatorProps>()

const collapsible = useCollapsibleContext()

useForwardExpose()
</script>

<template>
  <ark.div v-bind="collapsible.getIndicatorProps()" :as-child="asChild">
    <slot />
  </ark.div>
</template>
