// packages/frameworks/react/src/number-input/number-input-context.tsx
import type { ReactNode } from 'react'
import { useNumberInputContext, type UseNumberInputContext } from './use-number-input-context'

export interface NumberInputContextProps {
  children: (context: UseNumberInputContext) => ReactNode
}

export const NumberInputContext = (props: NumberInputContextProps) =>
  props.children(useNumberInputContext())

// packages/frameworks/solid/src/number-input/number-input-context.tsx
import type { JSX } from 'solid-js'
import { useNumberInputContext, type UseNumberInputContext } from './use-number-input-context'

export interface NumberInputContextProps {
  children: (context: UseNumberInputContext) => JSX.Element
}

export const NumberInputContext = (props: NumberInputContextProps) =>
  props.children(useNumberInputContext())
