// packages/svelte/src/lib/components/progress/examples/linear/indeterminate.svelte
<script lang="ts">
  import { Progress } from '@ark-ui/svelte/progress'
  import styles from 'styles/progress.module.css'
</script>

<Progress.Root class={styles.Root} defaultValue={null}>
  <Progress.Label class={styles.Label}>Label</Progress.Label>
  <Progress.ValueText class={styles.ValueText} />
  <Progress.Track class={styles.Track}>
    <Progress.Range class={styles.Range} />
  </Progress.Track>
</Progress.Root>

// packages/react/src/components/progress/examples/linear/indeterminate.tsx
import { Progress } from '@ark-ui/react/progress'
import styles from 'styles/progress.module.css'

export const Indeterminate = () => (
  <Progress.Root className={styles.Root} defaultValue={null}>
    <Progress.Label className={styles.Label}>Label</Progress.Label>
    <Progress.ValueText className={styles.ValueText} />
    <Progress.Track className={styles.Track}>
      <Progress.Range className={styles.Range} />
    </Progress.Track>
  </Progress.Root>
)
