// packages/react/src/components/rating-group/examples/half-star.tsx
import { RatingGroup } from '@ark-ui/react/rating-group'
import { StarIcon } from 'lucide-react'
import styles from 'styles/rating-group.module.css'

export const HalfStar = () => (
  <RatingGroup.Root className={styles.Root} defaultValue={2.5} allowHalf>
    <RatingGroup.Label className={styles.Label}>Label</RatingGroup.Label>
    <RatingGroup.Control className={styles.Control}>
      <RatingGroup.Context>
        {({ items }) =>
          items.map((item) => (
            <RatingGroup.Item className={styles.Item} key={item} index={item}>
              <RatingGroup.ItemContext>
                {({ half, highlighted }) => (
                  <span
                    className={styles.ItemIndicator}
                    data-half={half ? '' : undefined}
                    data-highlighted={highlighted ? '' : undefined}
                  >
                    <StarIcon data-bg="" />
                    <StarIcon data-fg="" fill="currentColor" />
                  </span>
                )}
              </RatingGroup.ItemContext>
            </RatingGroup.Item>
          ))
        }
      </RatingGroup.Context>
      <RatingGroup.HiddenInput />
    </RatingGroup.Control>
  </RatingGroup.Root>
)

// packages/vue/src/components/rating-group/examples/half-star.vue
<script setup lang="ts">
import { RatingGroup } from '@ark-ui/vue/rating-group'
import { StarIcon } from 'lucide-vue-next'
import styles from 'styles/rating-group.module.css'
</script>

<template>
  <RatingGroup.Root :class="styles.Root" :default-value="2.5" allow-half>
    <RatingGroup.Label :class="styles.Label">Label</RatingGroup.Label>
    <RatingGroup.Control :class="styles.Control">
      <RatingGroup.Context v-slot="{ items }">
        <RatingGroup.Item v-for="item in items" :key="item" :class="styles.Item" :index="item">
          <RatingGroup.ItemContext v-slot="{ half, highlighted }">
            <span
              :class="styles.ItemIndicator"
              :data-half="half ? '' : undefined"
              :data-highlighted="highlighted ? '' : undefined"
            >
              <StarIcon data-bg="" />
              <StarIcon data-fg="" fill="currentColor" />
            </span>
          </RatingGroup.ItemContext>
        </RatingGroup.Item>
      </RatingGroup.Context>
      <RatingGroup.HiddenInput />
    </RatingGroup.Control>
  </RatingGroup.Root>
</template>
