// packages/vue/src/components/number-input/examples/render-fn.vue
<script setup lang="ts">
import { NumberInput } from '@ark-ui/vue/number-input'
</script>

<template>
  <NumberInput.Root>
    <NumberInput.Scrubber />
    <NumberInput.Context v-slot="numberInput">
      <NumberInput.Label>Label {{ numberInput.valueAsNumber }}</NumberInput.Label>
    </NumberInput.Context>
    <NumberInput.Input />
    <NumberInput.Control>
      <NumberInput.DecrementTrigger>-1</NumberInput.DecrementTrigger>
      <NumberInput.IncrementTrigger>+1</NumberInput.IncrementTrigger>
    </NumberInput.Control>
  </NumberInput.Root>
</template>

// packages/react/src/components/number-input/examples/render-fn.tsx
import { NumberInput } from '@ark-ui/react/number-input'

export const RenderFn = () => (
  <NumberInput.Root>
    <NumberInput.Scrubber />
    <NumberInput.Context>
      {(numberInput) => <NumberInput.Label>Label {numberInput.valueAsNumber}</NumberInput.Label>}
    </NumberInput.Context>
    <NumberInput.Input />
    <NumberInput.Control>
      <NumberInput.DecrementTrigger>-1</NumberInput.DecrementTrigger>
      <NumberInput.IncrementTrigger>+1</NumberInput.IncrementTrigger>
    </NumberInput.Control>
  </NumberInput.Root>
)
