// packages/svelte/src/lib/components/number-input/examples/render-fn.svelte
<script lang="ts">
  import { NumberInput } from '@ark-ui/svelte/number-input'
</script>

<NumberInput.Root>
  <NumberInput.Scrubber />
  <NumberInput.Context>
    {#snippet render(numberInput)}
      <NumberInput.Label>Count: {numberInput().value}</NumberInput.Label>
    {/snippet}
  </NumberInput.Context>
  <NumberInput.Control>
    <NumberInput.DecrementTrigger>-</NumberInput.DecrementTrigger>
    <NumberInput.Input />
    <NumberInput.IncrementTrigger>+</NumberInput.IncrementTrigger>
  </NumberInput.Control>
</NumberInput.Root>

// packages/react/src/components/number-input/examples/render-fn.tsx
import { NumberInput } from '@ark-ui/react/number-input'

export const RenderFn = () => (
  <NumberInput.Root>
    <NumberInput.Scrubber />
    <NumberInput.Context>
      {(numberInput) => <NumberInput.Label>Label {numberInput.valueAsNumber}</NumberInput.Label>}
    </NumberInput.Context>
    <NumberInput.Input />
    <NumberInput.Control>
      <NumberInput.DecrementTrigger>-1</NumberInput.DecrementTrigger>
      <NumberInput.IncrementTrigger>+1</NumberInput.IncrementTrigger>
    </NumberInput.Control>
  </NumberInput.Root>
)
