// frameworks/solid/src/components/color-picker/color-picker-area-thumb.tsx
import { mergeProps } from '@zag-js/solid'
import { type HTMLArkProps, ark } from '~/factory'
import { useColorPickerAreaContext } from './use-color-picker-area-context'
import { useColorPickerContext } from './use-color-picker-context'

export interface ColorPickerAreaThumbProps extends HTMLArkProps<'div'> {}

export const ColorPickerAreaThumb = (props: ColorPickerAreaThumbProps) => {
  const colorAreaProps = useColorPickerAreaContext()
  const api = useColorPickerContext()
  const mergedProps = mergeProps(() => api().getAreaThumbProps(colorAreaProps), props)

  return <ark.div {...mergedProps} />
}

// packages/solid/src/color-picker/color-picker-area-thumb.tsx
import { mergeProps } from 'solid-js'
import { ark, type HTMLArkProps } from '../factory'
import { useColorPickerAreaContext } from './color-picker-area-context'
import { useColorPickerContext } from './color-picker-context'

export type ColorPickerAreaThumbProps = HTMLArkProps<'div'>

export const ColorPickerAreaThumb = (props: ColorPickerAreaThumbProps) => {
  const colorPicker = useColorPickerContext()
  const area = useColorPickerAreaContext()

  const mergedProps = mergeProps(colorPicker().getAreaThumbProps(area), props)

  return <ark.div {...mergedProps} />
}
