// packages/svelte/src/lib/components/date-picker/date-picker-table-cell-trigger.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types.js'

  export interface DatePickerTableCellTriggerBaseProps extends PolymorphicProps<'button'> {}
  export interface DatePickerTableCellTriggerProps
    extends Assign<HTMLProps<'button'>, DatePickerTableCellTriggerBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Ark } from '../factory/index.js'
  import { useDatePickerContext } from './use-date-picker-context.js'
  import { useDatePickerTableCellPropsContext } from './use-date-picker-table-cell-props-context.js'
  import { useDatePickerViewPropsContext } from './use-date-picker-view-props-context.js'

  const props: DatePickerTableCellTriggerProps = $props()

  const datePicker = useDatePickerContext()
  const cellProps = useDatePickerTableCellPropsContext()
  const viewProps = useDatePickerViewPropsContext()

  const triggerProps = $derived.by(() => {
    const viewMap = {
      day: datePicker().getDayTableCellTriggerProps,
      month: datePicker().getMonthTableCellTriggerProps,
      year: datePicker().getYearTableCellTriggerProps,
    }

    // @ts-expect-error fix later
    const viewFn = viewMap[viewProps().view]

    return viewFn(cellProps())
  })

  const mergedProps = $derived(mergeProps(triggerProps, props))
</script>

<Ark as="button" {...mergedProps} />

// packages/react/src/components/date-picker/date-picker-table-cell-trigger.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory'
import { useDatePickerContext } from './use-date-picker-context'
import { useDatePickerTableCellPropsContext } from './use-date-picker-table-cell-props-context'
import { useDatePickerViewPropsContext } from './use-date-picker-view-props-context'

export interface DatePickerTableCellTriggerBaseProps extends PolymorphicProps {}
export interface DatePickerTableCellTriggerProps extends HTMLProps<'div'>, DatePickerTableCellTriggerBaseProps {}

export const DatePickerTableCellTrigger = ({ ref, ...props }: DatePickerTableCellTriggerProps) => {
  const datePicker = useDatePickerContext()
  const tableCellProps = useDatePickerTableCellPropsContext()
  const viewProps = useDatePickerViewPropsContext()

  const viewMap = {
    day: datePicker.getDayTableCellTriggerProps,
    month: datePicker.getMonthTableCellTriggerProps,
    year: datePicker.getYearTableCellTriggerProps,
  }

  const viewFn = viewMap[viewProps.view]

  // @ts-expect-error fix later
  const triggerProps = viewFn(tableCellProps)

  const mergedProps = mergeProps(triggerProps, props)

  return <ark.div ref={ref} {...mergedProps} />
}

DatePickerTableCellTrigger.displayName = 'DatePickerTableCellTrigger'
