// packages/vue/src/components/focus-trap/focus-trap.vue
<script lang="ts">
import type { HTMLAttributes, VNodeRef } from 'vue'
import type { PolymorphicProps } from '../factory'
import type { BaseProps, BaseEmits } from './focus-trap.types'

export interface FocusTrapBaseProps extends BaseProps, PolymorphicProps {}
export interface FocusTrapProps
  extends FocusTrapBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
export interface FocusTrapEmits extends BaseEmits {}
</script>

<script setup lang="ts">
import { trapFocus, type FocusTrapOptions } from '@zag-js/focus-trap'
import { watchEffect, ref, onWatcherCleanup, onBeforeUnmount } from 'vue'
import { ark } from '../factory'
import { useForwardExpose, cleanProps } from '../../utils'

const props = withDefaults(defineProps<FocusTrapProps>(), {
  disabled: undefined,
  allowOutsideClick: undefined,
  returnFocusOnDeactivate: undefined,
  escapeDeactivates: undefined,
  clickOutsideDeactivates: undefined,
  preventScroll: undefined,
  delayInitialFocus: undefined,
  initialFocus: undefined,
  fallbackFocus: undefined,
  setReturnFocus: undefined,
  checkCanFocusTrap: undefined,
  checkCanReturnFocus: undefined,
  isKeyForward: undefined,
  isKeyBackward: undefined,
})

const emits = defineEmits<BaseEmits>()

const nodeRef = ref<VNodeRef | null>(null)
let cleanup: (() => void) | undefined

watchEffect(() => {
  if (props.disabled) return
  if (!nodeRef.value) return
  const node: HTMLElement | null = nodeRef.value.$el ? nodeRef.value.$el : nodeRef.value
  if (!node) return
  const autoFocusNode = node.querySelector<HTMLElement>('[autofocus], [data-autofocus]')

  const trapProps = cleanProps(props) as FocusTrapOptions
  trapProps.initialFocus ||= autoFocusNode ?? undefined

  cleanup = trapFocus(node, {
    ...trapProps,
    onActivate: () => emits('activate'),
    onDeactivate: () => emits('deactivate'),
    onPause: () => emits('pause'),
    onUnpause: () => emits('unpause'),
    onPostActivate: () => emits('post-activate'),
    onPostDeactivate: () => emits('post-deactivate'),
    onPostPause: () => emits('post-pause'),
    onPostUnpause: () => emits('post-unpause'),
  })

  onWatcherCleanup(() => cleanup?.())
})

onBeforeUnmount(() => {
  cleanup?.()
})

useForwardExpose()
</script>

<template>
  <ark.div ref="nodeRef" :as-child="asChild">
    <slot />
  </ark.div>
</template>

// packages/solid/src/components/focus-trap/focus-trap.tsx
import { type FocusTrapOptions, trapFocus } from '@zag-js/focus-trap'
import { createEffect, onCleanup } from 'solid-js'
import type { Assign } from '../../types'
import { composeRefs } from '../../utils/compose-refs'
import { createSplitProps } from '../../utils/create-split-props'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory'

export interface TrapOptions extends Omit<FocusTrapOptions, 'document' | 'trapStack'> {
  disabled?: boolean
}

export interface FocusTrapBaseProps extends PolymorphicProps<'div'>, TrapOptions {}
export interface FocusTrapProps extends Assign<HTMLProps<'div'>, FocusTrapBaseProps> {}

export const FocusTrap = (props: FocusTrapProps) => {
  let localNode!: HTMLDivElement

  const [trapProps, localProps] = createSplitProps<TrapOptions>()(props, [
    'disabled',
    'onActivate',
    'onPostActivate',
    'onPause',
    'onPostPause',
    'onUnpause',
    'onPostUnpause',
    'checkCanFocusTrap',
    'onDeactivate',
    'onPostDeactivate',
    'checkCanReturnFocus',
    'initialFocus',
    'fallbackFocus',
    'returnFocusOnDeactivate',
    'setReturnFocus',
    'escapeDeactivates',
    'clickOutsideDeactivates',
    'allowOutsideClick',
    'preventScroll',
    'delayInitialFocus',
    'isKeyForward',
    'isKeyBackward',
  ])

  createEffect(() => {
    if (!localNode || trapProps.disabled) return
    const autoFocusNode = localNode.querySelector<HTMLElement>('[autofocus], [data-autofocus]')
    trapProps.initialFocus ||= autoFocusNode ?? undefined
    onCleanup(trapFocus(localNode, trapProps))
  })

  // biome-ignore lint/suspicious/noAssignInExpressions: <explanation>
  return <ark.div {...localProps} ref={composeRefs((el) => (localNode = el), props.ref)} />
}
