// packages/frameworks/vue/src/popover/popover-trigger.tsx
import { defineComponent } from 'vue'
import { ark, type HTMLArkProps } from '../factory'
import { usePopoverContext } from './popover-context'

export interface PopoverTriggerProps extends HTMLArkProps<'button'> {}

export const PopoverTrigger = defineComponent({
  name: 'PopoverTrigger',
  setup(_, { slots, attrs }) {
    const api = usePopoverContext()

    return () => (
      <ark.button {...api.value.triggerProps} {...attrs}>
        {slots.default?.()}
      </ark.button>
    )
  },
})

// packages/solid/src/popover/popover-trigger.tsx
import { mergeProps } from '@zag-js/solid'
import { ark, type HTMLArkProps } from '../factory'
import { usePopoverContext } from './popover-context'

export type PopoverTriggerProps = HTMLArkProps<'button'>

export const PopoverTrigger = (props: PopoverTriggerProps) => {
  const api = usePopoverContext()
  const triggerProps = mergeProps(() => api().triggerProps, props)
  return <ark.button {...triggerProps} />
}
