// packages/vue/src/components/date-picker/date-picker-root-provider.vue
<script lang="ts">
import type { RootState } from '@zag-js/date-picker'
import type { HTMLAttributes, UnwrapRef } from 'vue'
import type { RenderStrategyProps } from '../../utils/use-render-strategy.ts'
import type { PolymorphicProps, PolymorphicSlots } from '../factory.ts'
import type { UseDatePickerReturn } from './use-date-picker.ts'
import type { RootEmits as PresenceEmits } from '../presence/presence.types.ts'

interface RootProviderProps {
  value: UnwrapRef<UseDatePickerReturn>
}

export interface DatePickerRootProviderState extends RootState {}
export interface DatePickerRootProviderBaseProps extends RootProviderProps, RenderStrategyProps, PolymorphicProps {}
export interface DatePickerRootProviderProps
  extends
    DatePickerRootProviderBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
export interface DatePickerRootProviderEmits extends PresenceEmits {}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { RenderStrategyPropsProvider } from '../../utils/use-render-strategy.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'
import { ark } from '../factory.ts'
import { PresenceProvider, usePresence } from '../presence/index.ts'
import { DatePickerProvider } from './use-date-picker-context.ts'

const props = defineProps<DatePickerRootProviderProps>()

defineSlots<PolymorphicSlots<DatePickerRootProviderState>>()
const emits = defineEmits<DatePickerRootProviderEmits>()

const datePicker = computed(() => props.value)

const presence = usePresence(
  computed(() => ({
    present: datePicker.value.open,
    lazyMount: props.lazyMount,
    unmountOnExit: props.unmountOnExit,
  })),
  emits,
)

DatePickerProvider(datePicker)
PresenceProvider(presence)
RenderStrategyPropsProvider(computed(() => ({ lazyMount: props.lazyMount, unmountOnExit: props.unmountOnExit })))

useForwardExpose()
</script>

<template>
  <ark.div v-bind="datePicker.getRootProps()" :state="datePicker.getRootState()" :as-child="asChild">
    <template v-if="$slots.render" #render="scope">
      <slot name="render" v-bind="scope" />
    </template>
    <template v-else #default>
      <slot />
    </template>
  </ark.div>
</template>

// packages/svelte/src/lib/components/date-picker/date-picker-root-provider.svelte
<script module lang="ts">
  import type { RootState } from '@zag-js/date-picker'
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types.js'
  import type { UsePresenceProps } from '../presence/index.js'
  import type { UseDatePickerReturn } from './use-date-picker.svelte.js'

  interface RootProviderProps {
    value: UseDatePickerReturn
  }

  export interface DatePickerRootProviderState extends RootState {}
  export interface DatePickerRootProviderBaseProps
    extends RootProviderProps, UsePresenceProps, PolymorphicProps<'div', DatePickerRootProviderState> {}
  export interface DatePickerRootProviderProps extends Assign<HTMLProps<'div'>, DatePickerRootProviderBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Ark } from '../factory/index.js'
  import { PresenceProvider, splitPresenceProps, usePresence } from '../presence/index.js'
  import { DatePickerProvider } from './use-date-picker-context.js'

  const { value, ...props }: DatePickerRootProviderProps = $props()

  const [presenceProps, localProps] = $derived(splitPresenceProps(props))

  const presence = usePresence(() => ({ present: value().open, ...presenceProps }))
  const mergedProps = $derived(mergeProps(value().getRootProps(), localProps))

  DatePickerProvider(() => value())
  PresenceProvider(presence)
</script>

<Ark as="div" {...mergedProps} state={value().getRootState()} />
