// packages/solid/src/components/menu/menu-context-trigger.tsx
import { mergeProps } from '@zag-js/solid'
import type { JSX } from 'solid-js'
import { type PolymorphicProps, ark } from '../factory'
import { useMenuContext } from './use-menu-context'

export interface MenuContextTriggerBaseProps extends PolymorphicProps<'button'> {}
export interface MenuContextTriggerProps
  extends JSX.HTMLAttributes<HTMLButtonElement>,
    MenuContextTriggerBaseProps {}

export const MenuContextTrigger = (props: MenuContextTriggerProps) => {
  const context = useMenuContext()
  const mergedProps = mergeProps(() => context().getContextTriggerProps(), props)

  return <ark.button {...mergedProps} />
}

// packages/react/src/components/menu/menu-context-trigger.tsx
import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory'
import { useMenuContext } from './use-menu-context'

export interface MenuContextTriggerBaseProps extends PolymorphicProps {}
export interface MenuContextTriggerProps extends HTMLProps<'button'>, MenuContextTriggerBaseProps {}

export const MenuContextTrigger = forwardRef<HTMLButtonElement, MenuContextTriggerProps>(
  (props, ref) => {
    const menu = useMenuContext()
    const mergedProps = mergeProps(menu.getContextTriggerProps(), props)

    return <ark.button {...mergedProps} ref={ref} />
  },
)

MenuContextTrigger.displayName = 'MenuContextTrigger'
