// packages/svelte/src/lib/components/menu/menu-list.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface MenuListBaseProps extends PolymorphicProps<'div'>, RefAttribute {}
  export interface MenuListProps extends Assign<HTMLProps<'div'>, MenuListBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Ark } from '../factory/index.ts'
  import { useMenuContext } from './use-menu-context.ts'

  let { ref = $bindable(null), ...props }: MenuListProps = $props()

  const menu = useMenuContext()
  const mergedProps = $derived(mergeProps(menu().getListProps(), props))
</script>

<Ark as="div" bind:ref {...mergedProps} />

// packages/react/src/components/menu/menu-list.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory.ts'
import { useMenuContext } from './use-menu-context.ts'

export interface MenuListBaseProps extends PolymorphicProps {}
export interface MenuListProps extends HTMLProps<'div'>, MenuListBaseProps {}

export const MenuList = forwardRef<HTMLDivElement, MenuListProps>((props, ref) => {
  const menu = useMenuContext()
  const mergedProps = mergeProps(menu.getListProps(), props)

  return <ark.div {...mergedProps} ref={ref} />
})

MenuList.displayName = 'MenuList'
