// frameworks/solid/src/components/menu/use-menu-item-context.ts
import type { OptionItemState } from '@zag-js/menu'
import type { Accessor } from 'solid-js'
import type { Optional } from '../../types'
import { createContext } from '../../utils/create-context'

export interface UseMenuItemContext extends Accessor<Optional<OptionItemState, 'checked'>> {}

export const [MenuItemProvider, useMenuItemContext] = createContext<UseMenuItemContext>({
  hookName: 'useMenuItemContext',
  providerName: '<MenuItemProvider />',
})

// packages/react/src/components/menu/use-menu-item-context.ts
'use client'

import type { OptionItemState } from '@zag-js/menu'
import type { Optional } from '../../types.ts'
import { createContext } from '../../utils/create-context.ts'

export interface UseMenuItemContext extends Optional<OptionItemState, 'checked'> {}

export const [MenuItemProvider, useMenuItemContext] = createContext<UseMenuItemContext>({
  name: 'MenuItemContext',
  hookName: 'useMenuItemContext',
  providerName: '<MenuItemProvider />',
})
