// packages/react/src/components/pin-input/pin-input-context.tsx
import type { ReactNode } from 'react'
import { type UsePinInputContext, usePinInputContext } from './use-pin-input-context'

export interface PinInputContextProps {
  children: (context: UsePinInputContext) => ReactNode
}

export const PinInputContext = (props: PinInputContextProps) => props.children(usePinInputContext())

// frameworks/solid/src/pin-input/pin-input-context.tsx
import type { JSX } from 'solid-js'
import { usePinInputContext, type UsePinInputContext } from './use-pin-input-context'

export interface PinInputContextProps {
  children: (context: UsePinInputContext) => JSX.Element
}

export const PinInputContext = (props: PinInputContextProps) => props.children(usePinInputContext())
