// packages/vue/src/toggle/use-toggle.tsx
import * as toggle from '@zag-js/toggle'
import { normalizeProps, useMachine, type PropTypes } from '@zag-js/vue'
import { computed, ref, type ComputedRef } from 'vue'
import { useEnvironmentContext } from '../environment'
import type { Optional } from '../types'
import { useId } from '../utils'

export type UseToggleProps = Optional<toggle.Context, 'id'>
export type UseToggleReturn = ComputedRef<toggle.Api<PropTypes>>

export const useToggle = (props: UseToggleProps, emit: CallableFunction): UseToggleReturn => {
  const getRootNode = useEnvironmentContext()
  const context = ref(props)

  const [state, send] = useMachine(
    toggle.machine({
      ...context.value,
      id: context.value.id ?? useId().value,
      getRootNode,
      onChange: (value) => {
        emit('change', value)
      },
    }),
    { context },
  )
  return computed(() => toggle.connect(state.value, send, normalizeProps))
}

// packages/react/src/toggle/use-toggle.ts
import { normalizeProps, useMachine } from '@zag-js/react'
import * as toggle from '@zag-js/toggle'
import { useId } from 'react'
import { useEnvironmentContext } from '../environment'
import { type Optional } from '../types'

export interface UseToggleProps extends Optional<toggle.Context, 'id'> {}
export type UseToggleReturn = toggle.Api

export const useToggle = (props: UseToggleProps): UseToggleReturn => {
  const getRootNode = useEnvironmentContext()
  const context = {
    id: useId(),
    getRootNode,
    ...props,
  }
  const [state, send] = useMachine(toggle.machine(context), { context })
  return toggle.connect(state, send, normalizeProps)
}
