// packages/svelte/src/lib/components/image-cropper/image-cropper-root-provider.svelte
<script module lang="ts">
  import type { RootState } from '@zag-js/image-cropper'
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'
  import type { UseImageCropperReturn } from './use-image-cropper.svelte.ts'

  export interface ImageCropperRootProviderState extends RootState {}
  export interface ImageCropperRootProviderBaseProps
    extends PolymorphicProps<'div', ImageCropperRootProviderState>, RefAttribute {
    value: UseImageCropperReturn
  }
  export interface ImageCropperRootProviderProps extends Assign<HTMLProps<'div'>, ImageCropperRootProviderBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { ImageCropperProvider } from './use-image-cropper-context.ts'
  import { Ark } from '../factory/index.ts'

  let { ref = $bindable(null), value, ...props }: ImageCropperRootProviderProps = $props()

  const mergedProps = $derived(mergeProps(value().getRootProps(), props))

  ImageCropperProvider(() => value())
</script>

<Ark as="div" bind:ref {...mergedProps} state={value().getRootState()} />

// packages/react/src/components/image-cropper/image-cropper-root-provider.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { createSplitProps } from '../../utils/create-split-props.ts'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory.ts'
import type { UseImageCropperReturn } from './use-image-cropper.ts'
import { ImageCropperProvider } from './use-image-cropper-context.ts'
import type { RootState } from '@zag-js/image-cropper'

interface RootProviderProps {
  value: UseImageCropperReturn
}

export interface ImageCropperRootProviderState extends RootState {}

export interface ImageCropperRootProviderBaseProps
  extends RootProviderProps, PolymorphicProps<ImageCropperRootProviderState> {}
export interface ImageCropperRootProviderProps extends HTMLProps<'div'>, ImageCropperRootProviderBaseProps {}

const splitRootProviderProps = createSplitProps<RootProviderProps>()

export const ImageCropperRootProvider = forwardRef<HTMLDivElement, ImageCropperRootProviderProps>((props, ref) => {
  const [{ value: imageCropper }, localProps] = splitRootProviderProps(props, ['value'])
  const mergedProps = mergeProps(imageCropper.getRootProps(), localProps)

  return (
    <ImageCropperProvider value={imageCropper}>
      <ark.div {...mergedProps} ref={ref} state={imageCropper.getRootState()} />
    </ImageCropperProvider>
  )
})

ImageCropperRootProvider.displayName = 'ImageCropperRootProvider'
