// packages/angular/field/examples/item.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import {
  ArkFieldErrorText,
  ArkFieldHelperText,
  ArkFieldInput,
  ArkFieldItem,
  ArkFieldLabel,
  ArkFieldRoot,
  ArkFieldSelect,
} from '@ark-ui/angular/field'
import { fieldExampleStyles } from '../field-example-styles'

@Component({
  selector: 'field-item-example',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    ArkFieldRoot,
    ArkFieldLabel,
    ArkFieldItem,
    ArkFieldInput,
    ArkFieldSelect,
    ArkFieldHelperText,
    ArkFieldErrorText,
  ],
  template: `
    <div arkFieldRoot target="amount">
      <label arkFieldLabel>Amount</label>
      <div arkFieldItem value="currency">
        <select arkFieldSelect>
          <option value="USD">USD</option>
          <option value="EUR">EUR</option>
        </select>
      </div>
      <div arkFieldItem value="amount">
        <input arkFieldInput />
      </div>
      <span arkFieldHelperText>Enter the amount</span>
      <span arkFieldErrorText>Invalid amount</span>
    </div>
  `,
  styles: [fieldExampleStyles],
})
export class FieldItemExample {}

// packages/react/src/components/field/examples/item.tsx
import { Field } from '@ark-ui/react/field'
import styles from 'styles/field.module.css'

export const Item = () => (
  <Field.Root className={styles.Root} target="amount">
    <Field.Label className={styles.Label}>Amount</Field.Label>
    <Field.Item value="currency">
      <Field.Select className={styles.Select}>
        <option value="USD">USD</option>
        <option value="EUR">EUR</option>
      </Field.Select>
    </Field.Item>
    <Field.Item value="amount">
      <Field.Input className={styles.Input} />
    </Field.Item>
    <Field.HelperText className={styles.HelperText}>Enter the amount</Field.HelperText>
    <Field.ErrorText className={styles.ErrorText}>Invalid amount</Field.ErrorText>
  </Field.Root>
)
