// packages/solid/src/number-input/number-input-label.tsx
import { ark, type HTMLArkProps } from '../factory'
import { useNumberInputContext } from './number-input-context'

export type NumberInputLabelProps = HTMLArkProps<'label'>

export const NumberInputLabel = (props: NumberInputLabelProps) => {
  const numberInput = useNumberInputContext()

  return <ark.label {...numberInput().labelProps} {...props} />
}

// frameworks/vue/src/components/number-input/number-input-label.tsx
import { defineComponent } from 'vue'
import { type HTMLArkProps, ark } from '../../factory'
import { useNumberInputContext } from './number-input-context'

export interface NumberInputLabelProps extends HTMLArkProps<'label'> {}

export const NumberInputLabel = defineComponent<NumberInputLabelProps>(
  (_, { slots, attrs }) => {
    const api = useNumberInputContext()

    return () => (
      <ark.label {...api.value.labelProps} {...attrs}>
        {slots.default?.()}
      </ark.label>
    )
  },
  {
    name: 'NumberInputLabel',
  },
)
