// packages/solid/src/components/virtualizer/grid-virtualizer-context.tsx
import type { JSX } from 'solid-js'
import { type UseGridVirtualizerContext, useGridVirtualizerContext } from './use-grid-virtualizer-context.ts'

export interface GridVirtualizerContextProps {
  children: (context: UseGridVirtualizerContext) => JSX.Element
}

export const GridVirtualizerContext = (props: GridVirtualizerContextProps) =>
  props.children(useGridVirtualizerContext())

// packages/react/src/components/virtualizer/grid-virtualizer-context.tsx
'use client'

import type { ReactNode } from 'react'
import { type UseGridVirtualizerContext, useGridVirtualizerContext } from './use-grid-virtualizer-context.ts'

export interface GridVirtualizerContextProps {
  children: (context: UseGridVirtualizerContext) => ReactNode
}

export const GridVirtualizerContext = (props: GridVirtualizerContextProps) =>
  props.children(useGridVirtualizerContext())
