// packages/svelte/src/lib/components/virtualizer/window-virtualizer-root.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types.js'
  import type { UseWindowVirtualizerReturn } from './use-window-virtualizer.svelte.ts'

  export interface WindowVirtualizerRootBaseProps extends PolymorphicProps<'div'>, RefAttribute {
    /**
     * The virtualizer instance returned by `useWindowVirtualizer`.
     */
    value: UseWindowVirtualizerReturn
  }
  export interface WindowVirtualizerRootProps extends Assign<HTMLProps<'div'>, WindowVirtualizerRootBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Ark } from '../factory/index.js'
  import { WindowVirtualizerProvider } from './use-window-virtualizer-context.ts'

  let { ref = $bindable(null), value, ...props }: WindowVirtualizerRootProps = $props()

  const mergedProps = $derived(mergeProps(value.getContainerAriaAttrs(), { style: value.getContainerStyle() }, props))

  WindowVirtualizerProvider(() => value)

  $effect(() => {
    value.ref(ref instanceof HTMLElement ? ref : null)
  })
</script>

<Ark as="div" bind:ref {...mergedProps} />

// packages/react/src/components/virtualizer/window-virtualizer-root.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { useComposedRefs } from '../../utils/compose-refs.ts'
import { createSplitProps } from '../../utils/create-split-props.ts'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory.ts'
import type { UseWindowVirtualizerReturn } from './use-window-virtualizer.ts'
import { WindowVirtualizerProvider } from './use-window-virtualizer-context.ts'

interface RootProps {
  /**
   * The virtualizer instance returned by `useWindowVirtualizer`.
   */
  value: UseWindowVirtualizerReturn
}

export interface WindowVirtualizerRootBaseProps extends RootProps, PolymorphicProps {}

export interface WindowVirtualizerRootProps extends HTMLProps<'div'>, WindowVirtualizerRootBaseProps {}

const splitRootProps = createSplitProps<RootProps>()

export const WindowVirtualizerRoot = forwardRef<HTMLDivElement, WindowVirtualizerRootProps>((props, ref) => {
  const [{ value: virtualizer }, localProps] = splitRootProps(props, ['value'])
  const composedRef = useComposedRefs(virtualizer.ref, ref)
  const mergedProps = mergeProps(
    { ...virtualizer.getContainerAriaAttrs(), style: virtualizer.getContainerStyle() },
    localProps,
  )

  return (
    <WindowVirtualizerProvider value={virtualizer}>
      <ark.div {...mergedProps} ref={composedRef} />
    </WindowVirtualizerProvider>
  )
})

WindowVirtualizerRoot.displayName = 'WindowVirtualizerRoot'
