// packages/frameworks/solid/src/number-input/number-input-increment-trigger.tsx
import { mergeProps } from '@zag-js/solid'
import { ark, type HTMLArkProps } from '../factory'
import { useNumberInputContext } from './number-input-context'

export interface NumberInputIncrementTriggerProps extends HTMLArkProps<'button'> {}

export const NumberInputIncrementTrigger = (props: NumberInputIncrementTriggerProps) => {
  const api = useNumberInputContext()
  const triggerProps = mergeProps(() => api().incrementTriggerProps, props)
  return <ark.button {...triggerProps} />
}

// packages/frameworks/vue/src/number-input/number-input-increment-trigger.tsx
import { defineComponent } from 'vue'
import { ark, type HTMLArkProps } from '../factory'
import { useNumberInputContext } from './number-input-context'

export interface NumberInputIncrementTriggerProps extends HTMLArkProps<'button'> {}

export const NumberInputIncrementTrigger = defineComponent({
  name: 'NumberInputIncrementTrigger',
  setup(_, { slots, attrs }) {
    const api = useNumberInputContext()

    return () => (
      <ark.button {...api.value.incrementTriggerProps} {...attrs}>
        {slots.default?.()}
      </ark.button>
    )
  },
})
