// packages/react/src/components/date-input/date-input-segment-context.tsx
import type { DateSegment } from '@zag-js/date-input'
import { Fragment, type ReactNode } from 'react'
import { useDateInputContext } from './use-date-input-context'
import { useDateInputSegmentGroupPropsContext } from './use-date-input-segment-group-props-context'

export interface DateInputSegmentContextProps {
  children: (segment: DateSegment) => ReactNode
}

export const DateInputSegmentContext = (props: DateInputSegmentContextProps) => {
  const dateInput = useDateInputContext()
  const segmentGroupProps = useDateInputSegmentGroupPropsContext()
  return dateInput
    .getSegments(segmentGroupProps)
    .map((segment, index) => <Fragment key={`${segment.type}-${index}`}>{props.children(segment)}</Fragment>)
}

// packages/vue/src/components/date-input/date-input-segment-context.vue
<script lang="ts">
import type { DateSegment } from '@zag-js/date-input'

export type DateInputSegmentContextProps = {}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { useDateInputContext } from './use-date-input-context.ts'
import { useDateInputSegmentGroupPropsContext } from './use-date-input-segment-group-props-context.ts'

const dateInput = useDateInputContext()
const segmentGroupProps = useDateInputSegmentGroupPropsContext()

const keyedSegments = computed(() =>
  dateInput.value.getSegments(segmentGroupProps!.value).map((segment, index) => ({
    ...segment,
    key: `${segment.type}-${index}`,
  })),
)

defineSlots<{
  default(segment: DateSegment): unknown
}>()
</script>

<template>
  <template v-for="segment in keyedSegments" :key="segment.key">
    <slot v-bind="segment" />
  </template>
</template>
