// packages/solid/src/rating/rating-item.tsx
import { splitProps } from 'solid-js'
import type { JSX } from 'solid-js/jsx-runtime'
import { ark, HTMLArkProps } from '../factory'
import { useRatingContext } from './rating-context'
import { RatingItemContext, RatingItemProvider } from './rating-item-context'

export type RenderIconFn = (state: RatingItemContext) => JSX.Element

export type RatingItemProps = Omit<HTMLArkProps<'span'>, 'children'> & {
  index: number
  children: JSX.Element | RenderIconFn
}

export const RatingItem = (props: RatingItemProps) => {
  const [localProps, spanProps] = splitProps(props, ['index', 'children'])

  const rating = useRatingContext()

  const state = rating().getRatingState(localProps.index)
  const icon =
    typeof localProps.children === 'function' ? localProps.children(state) : localProps.children

  return (
    <ark.span {...rating().getItemProps({ index: localProps.index })} {...spanProps}>
      <RatingItemProvider value={state}>{icon}</RatingItemProvider>
    </ark.span>
  )
}

// packages/react/src/rating/rating-item.tsx
import type { ReactNode } from 'react'
import { atlas, HTMLAtlasProps } from '../factory'
import { forwardRef } from '../forwardRef'
import { useRatingContext } from './rating-context'
import { RatingItemContext, RatingItemProvider } from './rating-item-context'

export type RenderIconFn = (state: RatingItemContext) => ReactNode

export type RatingItemProps = Omit<HTMLAtlasProps<'span'>, 'children'> & {
  index: number
  children: ReactNode | RenderIconFn
}

export const RatingItem = forwardRef<'span', RatingItemProps>((props, ref) => {
  const { children, index, ...htmlProps } = props
  const api = useRatingContext()
  const state = api.getRatingState(index)
  const icon = typeof children === 'function' ? children(state) : children

  return (
    <atlas.span {...api.getItemProps({ index })} {...htmlProps} ref={ref}>
      <RatingItemProvider value={state}>{icon}</RatingItemProvider>
    </atlas.span>
  )
})
