// packages/react/src/components/navigation-menu/navigation-menu-item.tsx
'use client'

import type { ItemProps } from '@zag-js/navigation-menu'
import { mergeProps } from '@zag-js/react'
import { createSplitProps } from '../../utils/create-split-props'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory'
import { useNavigationMenuContext } from './use-navigation-menu-context'
import { NavigationMenuItemPropsProvider } from './use-navigation-menu-item-props-context'

export interface NavigationMenuItemBaseProps extends ItemProps, PolymorphicProps {}
export interface NavigationMenuItemProps extends HTMLProps<'div'>, NavigationMenuItemBaseProps {}

const splitItemProps = createSplitProps<ItemProps>()

export const NavigationMenuItem = ({ ref, ...props }: NavigationMenuItemProps) => {
  const [itemProps, localProps] = splitItemProps(props, ['disabled', 'value'])
  const navigationMenu = useNavigationMenuContext()
  const mergedProps = mergeProps(navigationMenu.getItemProps(itemProps), localProps)

  return (
    <NavigationMenuItemPropsProvider value={itemProps}>
      <ark.div {...mergedProps} ref={ref} />
    </NavigationMenuItemPropsProvider>
  )
}

NavigationMenuItem.displayName = 'NavigationMenuItem'

// packages/vue/src/components/navigation-menu/navigation-menu-item.vue
<script lang="ts">
import type { ItemProps } from '@zag-js/navigation-menu'
import type { HTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory'

export interface NavigationMenuItemBaseProps extends ItemProps, PolymorphicProps {}
export interface NavigationMenuItemProps
  extends NavigationMenuItemBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { ark } from '../factory'
import { useNavigationMenuContext } from './use-navigation-menu-context'
import { NavigationMenuItemPropsProvider } from './use-navigation-menu-item-props-context'
import { useForwardExpose } from '../../utils/use-forward-expose'

const props = defineProps<NavigationMenuItemProps>()
const navigationMenu = useNavigationMenuContext()

const itemProps = computed(() => ({ value: props.value, disabled: props.disabled }))
NavigationMenuItemPropsProvider(itemProps)

useForwardExpose()
</script>

<template>
  <ark.div v-bind="navigationMenu.getItemProps(props)" :as-child="asChild">
    <slot />
  </ark.div>
</template>
