// packages/svelte/src/lib/components/format/examples/relative-time-short.svelte
<script lang="ts">
  import { Format } from '@ark-ui/svelte/format'
  import styles from 'styles/format.module.css'
</script>

<div class={styles.Inline}>
  <span class={styles.InlineLabel}>Edited</span>
  <span class={styles.InlineValue}>
    <Format.RelativeTime value={new Date('2025-05-05')} style="short" />
  </span>
</div>

// packages/react/src/components/format/examples/relative-time-short.tsx
import { Format } from '@ark-ui/react/format'
import styles from 'styles/format.module.css'

export const RelativeTimeShort = () => {
  return (
    <div className={styles.Inline}>
      <span className={styles.InlineLabel}>Edited</span>
      <span className={styles.InlineValue}>
        <Format.RelativeTime value={new Date('2025-05-05')} style="short" />
      </span>
    </div>
  )
}
