// packages/svelte/src/lib/components/signature-pad/signature-pad-root.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'
  import type { UseSignaturePadProps } from './use-signature-pad.svelte'

  export interface SignaturePadRootBaseProps extends UseSignaturePadProps, PolymorphicProps<'div'> {}
  export interface SignaturePadRootProps extends Assign<HTMLProps<'div'>, SignaturePadRootBaseProps> {}
</script>

<script lang="ts">
  import { createSplitProps } from '$lib/utils/create-split-props'
  import { mergeProps } from '@zag-js/svelte'
  import { Ark } from '../factory'
  import { useSignaturePad } from './use-signature-pad.svelte'
  import { SignaturePadProvider } from './use-signature-pad-context'

  const props: SignaturePadRootProps = $props()
  const providedId = $props.id()

  const [useSignaturePadProps, localProps] = $derived(
    createSplitProps<UseSignaturePadProps>()(props, [
      'id',
      'ids',
      'drawing',
      'disabled',
      'readOnly',
      'name',
      'onDraw',
      'onDrawEnd',
      'required',
      'translations',
    ]),
  )

  const resolvedProps = $derived<UseSignaturePadProps>({
    ...useSignaturePadProps,
    id: useSignaturePadProps.id ?? providedId,
  })

  const signaturePad = useSignaturePad(() => resolvedProps)
  const mergedProps = $derived(mergeProps(signaturePad().getRootProps(), localProps))

  SignaturePadProvider(signaturePad)
</script>

<Ark as="div" {...mergedProps} />

// packages/react/src/components/signature-pad/signature-pad-root.tsx
import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { createSplitProps } from '../../utils/create-split-props'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory'
import { type UseSignaturePadProps, useSignaturePad } from './use-signature-pad'
import { SignaturePadProvider } from './use-signature-pad-context'

export interface SignaturePadRootBaseProps extends UseSignaturePadProps, PolymorphicProps {}
export interface SignaturePadRootProps extends HTMLProps<'div'>, SignaturePadRootBaseProps {}
export const SignaturePadRoot = forwardRef<HTMLDivElement, SignaturePadRootProps>((props, ref) => {
  const [useSignaturePadProps, localProps] = createSplitProps<UseSignaturePadProps>()(props, [
    'id',
    'ids',
    'drawing',
    'disabled',
    'readOnly',
    'name',
    'onDraw',
    'onDrawEnd',
    'readOnly',
    'required',
    'translations',
  ])
  const signaturePad = useSignaturePad(useSignaturePadProps)
  const mergedProps = mergeProps(signaturePad.getRootProps(), localProps)

  return (
    <SignaturePadProvider value={signaturePad}>
      <ark.div {...mergedProps} ref={ref} />
    </SignaturePadProvider>
  )
})

SignaturePadRoot.displayName = 'SignaturePadRoot'
