// packages/solid/src/components/marquee/marquee-item.tsx
import { mergeProps } from '@zag-js/solid'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory'
import { useMarqueeContext } from './use-marquee-context'

export interface MarqueeItemBaseProps extends PolymorphicProps<'div'> {}
export interface MarqueeItemProps extends HTMLProps<'div'>, MarqueeItemBaseProps {}

export const MarqueeItem = (props: MarqueeItemProps) => {
  const context = useMarqueeContext()
  const mergedProps = mergeProps(() => context().getItemProps(), props)
  return <ark.div {...mergedProps} />
}

// packages/vue/src/components/marquee/marquee-item.vue
<script lang="ts">
import type { HTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory'

export interface MarqueeItemBaseProps extends PolymorphicProps {}
export interface MarqueeItemProps
  extends
    MarqueeItemBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
</script>

<script setup lang="ts">
import { ark } from '../factory'
import { useForwardExpose } from '../../utils/use-forward-expose'
import { useMarqueeContext } from './use-marquee-context'

defineProps<MarqueeItemProps>()
const marquee = useMarqueeContext()
useForwardExpose()
</script>

<template>
  <ark.div v-bind="marquee.getItemProps()" :as-child="asChild">
    <slot />
  </ark.div>
</template>
