// frameworks/vue/src/components/splitter/splitter-resize-trigger.tsx
import type { ResizeTriggerProps } from '@zag-js/splitter'
import { type PropType, defineComponent } from 'vue'
import type { Assign } from '../../types'
import { type HTMLArkProps, ark } from '../factory'
import { useSplitterContext } from './use-splitter-context'

export interface SplitterResizeTriggerProps
  extends Assign<HTMLArkProps<'button'>, ResizeTriggerProps> {}

export const SplitterResizeTrigger = defineComponent<SplitterResizeTriggerProps>(
  (props, { slots, attrs }) => {
    const api = useSplitterContext()

    return () => (
      <ark.button {...api.value.getResizeTriggerProps(props)} {...attrs}>
        {slots.default?.()}
      </ark.button>
    )
  },
  {
    name: 'SplitterResizeTrigger',
    props: {
      id: {
        type: String as PropType<SplitterResizeTriggerProps['id']>,
        required: true,
      },
      step: {
        type: Number as PropType<SplitterResizeTriggerProps['step']>,
      },
      disabled: {
        type: Boolean as PropType<SplitterResizeTriggerProps['disabled']>,
      },
    },
  },
)

// frameworks/solid/src/splitter/splitter-resize-trigger.tsx
import { mergeProps } from '@zag-js/solid'
import { type ResizeTriggerProps } from '@zag-js/splitter'
import { createSplitProps } from '../create-split-props'
import { ark, type HTMLArkProps } from '../factory'
import type { Assign } from '../types'
import { useSplitterContext } from './use-splitter-context'

export interface SplitterResizeTriggerProps
  extends Assign<HTMLArkProps<'button'>, ResizeTriggerProps> {}

export const SplitterResizeTrigger = (props: SplitterResizeTriggerProps) => {
  const [resizeTriggerProps, restProps] = createSplitProps<ResizeTriggerProps>()(props, [
    'disabled',
    'id',
    'step',
  ])
  const api = useSplitterContext()
  const mergedProps = mergeProps(() => api().getResizeTriggerProps(resizeTriggerProps), restProps)

  return <ark.button {...mergedProps} />
}
