// packages/svelte/src/lib/providers/locale/locale-provider.svelte
<script module lang="ts">
  import type { Locale } from '@zag-js/i18n-utils'
  import type { Snippet } from 'svelte'

  export interface LocaleProviderProps {
    /**
     * The locale to use for the application.
     * @default 'en-US'
     */
    locale: string
    /**
     * The children to render.
     */
    children?: Snippet
  }
</script>

<script lang="ts">
  import { isRTL } from '@zag-js/i18n-utils'
  import { LocaleContextProvider } from './use-locale-context'

  let { locale, children }: LocaleProviderProps = $props()

  const context = $state<Locale>({
    locale,
    dir: isRTL(locale) ? 'rtl' : 'ltr',
  })

  LocaleContextProvider(context)
</script>

{@render children?.()}

// packages/react/src/providers/locale/locale-provider.tsx
import { type Locale, isRTL } from '@zag-js/i18n-utils';
import type { PropsWithChildren } from 'react';
import { LocaleContextProvider } from './use-locale-context';

export interface LocaleProviderProps extends PropsWithChildren {
  /**
   * The locale to use for the application.
   * @default 'en-US'
   */
  locale: string
  dir?: "rtl" | "ltr"

}

export const LocaleProvider = (props: LocaleProviderProps) => {
  const { children, locale } = props

  const context: Locale = {
    locale,
    dir: props.dir ? props.dir : isRTL(props.locale) ? "rtl" : "ltr",
  }

  return <LocaleContextProvider value={context}>{children}</LocaleContextProvider>
}
