// packages/solid/src/components/tour/tour-close-trigger.tsx
import { mergeProps } from "@zag-js/solid";
import { type HTMLProps, type PolymorphicProps, ark } from "../factory";
import { useTourContext } from "./use-tour-context";

export interface TourCloseTriggerBaseProps extends PolymorphicProps<"button"> {}
export interface TourCloseTriggerProps
	extends HTMLProps<"button">,
		TourCloseTriggerBaseProps {}

export const TourCloseTrigger = (props: TourCloseTriggerProps) => {
	const tour = useTourContext();
	const mergedProps = mergeProps(() => tour().getCloseTriggerProps(), props);

	return <ark.button {...mergedProps} />;
};

// packages/svelte/src/lib/components/tour/tour-close-trigger.svelte
<script module lang="ts">
  import type { HTMLProps, PolymorphicProps } from '$lib/types'

  export interface TourCloseTriggerBaseProps extends PolymorphicProps<'button'> {}
  export interface TourCloseTriggerProps extends HTMLProps<'button'>, TourCloseTriggerBaseProps {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Ark } from '../factory'
  import { useTourContext } from './use-tour-context'

  const props: TourCloseTriggerProps = $props()

  const tour = useTourContext()

  const mergedProps = $derived(mergeProps(tour().getCloseTriggerProps(), props))
</script>

<Ark as="button" {...mergedProps} />
