// packages/solid/src/tags-input/tag-delete-trigger.tsx
import type { Assign } from '@polymorphic-factory/solid'
import { children, createEffect, JSX } from 'solid-js'
import { spread } from 'solid-js/web'
import { createSplitProps } from '../create-split-props'
import type { TagProps } from './tag'
import { useTagsInputContext } from './tags-input-context'

export type TagDeleteTriggerProps = Assign<{ children: JSX.Element }, TagProps>

export const TagDeleteTrigger = (props: TagDeleteTriggerProps) => {
  const [tagProps, localProps] = createSplitProps<TagProps>()(props, ['index', 'disabled', 'value'])
  const tagsInput = useTagsInputContext()

  const getChildren = children(() => localProps.children)

  createEffect(() => {
    const children = getChildren()
    if (children instanceof Element) {
      spread(children, { ...tagsInput().getTagDeleteButtonProps(tagProps) })
    }
  })

  return <>{getChildren()}</>
}

// packages/react/src/tags-input/tag-delete-trigger.tsx
import { Children, cloneElement, ReactElement } from 'react'
import { createSplitProps } from '../create-split-props'
import type { Assign } from '../types'
import type { TagProps } from './tag'
import { useTagsInputContext } from './tags-input-context'

export type TagDeleteTriggerProps = Assign<TagProps, { children: ReactElement }>

export const TagDeleteTrigger = (props: TagDeleteTriggerProps) => {
  const [tagProps, { children }] = createSplitProps<TagProps>()(props, [
    'index',
    'disabled',
    'value',
  ])
  const { getTagDeleteButtonProps } = useTagsInputContext()

  const onlyChild = Children.only(children)
  return cloneElement(onlyChild, getTagDeleteButtonProps(tagProps))
}
