// packages/vue/src/tags-input/tags-input-field.tsx
import { computed, defineComponent } from 'vue'
import { ark, type HTMLArkProps } from '../factory'
import type { ComponentWithProps } from '../utils'
import { useTagsInputContext } from './tags-input-context'

export type TagsInputFieldProps = HTMLArkProps<'input'>

export const TagsInputField: ComponentWithProps<TagsInputFieldProps> = defineComponent({
  name: 'TagsInputField',
  setup(_, { attrs }) {
    const api = useTagsInputContext()

    const inputProps = computed(() => ({
      ...api.value.inputProps,
      modelValue: api.value.inputValue,
    }))

    return () => <ark.input {...inputProps.value} {...attrs} />
  },
})

// packages/react/src/tags-input/tags-input-field.tsx
import { forwardRef } from '@polymorphic-factory/react'
import { mergeProps } from '@zag-js/react'
import { ark, HTMLArkProps } from '../factory'
import { useTagsInputContext } from './tags-input-context'

export type TagsInputFieldProps = HTMLArkProps<'input'>

export const TagsInputField = forwardRef<'input', TagsInputFieldProps>((props, ref) => {
  const { inputProps } = useTagsInputContext()
  const mergedProps = mergeProps(inputProps, props)

  return <ark.input {...mergedProps} ref={ref} />
})
