// packages/angular/editable/examples/textarea.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import {
  ArkEditableArea,
  ArkEditableInput,
  ArkEditableLabel,
  ArkEditablePreview,
  ArkEditableRoot,
} from '@ark-ui/angular/editable'
import { editableExampleStyles } from '../editable-example-styles'

@Component({
  selector: 'editable-textarea-example',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ArkEditableRoot, ArkEditableArea, ArkEditableInput, ArkEditableLabel, ArkEditablePreview],
  template: `
    <div
      arkEditableRoot
      placeholder="Enter a description..."
      defaultValue="Ark UI is a headless component library for building reusable, scalable design systems."
      activationMode="dblclick"
    >
      <span arkEditableLabel>Description</span>
      <div arkEditableArea>
        <textarea arkEditableInput class="textarea"></textarea>
        <span arkEditablePreview class="textarea"></span>
      </div>
      <div class="helper-text">Press Cmd + Enter to save</div>
    </div>
  `,
  styles: [editableExampleStyles],
})
export class EditableTextareaExample {}

// packages/react/src/components/editable/examples/textarea.tsx
import { Editable } from '@ark-ui/react/editable'
import styles from 'styles/editable.module.css'

export const Textarea = () => (
  <Editable.Root
    className={styles.Root}
    placeholder="Enter a description..."
    defaultValue="Ark UI is a headless component library for building reusable, scalable design systems."
    activationMode="dblclick"
  >
    <Editable.Label className={styles.Label}>Description</Editable.Label>
    <Editable.Area className={styles.Area}>
      <Editable.Input className={styles.Textarea} asChild>
        <textarea />
      </Editable.Input>
      <Editable.Preview className={styles.Textarea} />
    </Editable.Area>
    <div className={styles.HelperText}>Press Cmd + Enter to save</div>
  </Editable.Root>
)
