// packages/frameworks/react/src/menu/menu-option-item-text.tsx
import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { ark, type HTMLArkProps } from '../factory'
import { useMenuContext } from './menu-context'
import { type UseMenuReturn } from './use-menu'
import { useMenuOptionItemPropsContext } from './use-menu-option-item-context'

export interface MenuOptionItemTextProps extends HTMLArkProps<'div'> {}

export const MenuOptionItemText = forwardRef<HTMLDivElement, MenuOptionItemTextProps>(
  (props, ref) => {
    const api = useMenuContext() as UseMenuReturn['api']
    const optionItemProps = useMenuOptionItemPropsContext()
    const mergedProps = mergeProps(api?.getOptionItemTextProps(optionItemProps) ?? {}, props)

    return <ark.div {...mergedProps} ref={ref} />
  },
)

MenuOptionItemText.displayName = 'MenuOptionItemText'

// frameworks/vue/src/menu/menu-option-item-text.tsx
import { defineComponent } from 'vue'
import { ark, type HTMLArkProps } from '../factory'
import { useMenuContext } from './menu-context'
import { useMenuOptionItemPropsContext } from './use-menu-option-item-context'

export interface MenuOptionItemTextProps extends HTMLArkProps<'div'> {}

export const MenuOptionItemText = defineComponent<MenuOptionItemTextProps>(
  (_, { slots, attrs }) => {
    const api = useMenuContext()
    const optionItemProps = useMenuOptionItemPropsContext()

    return () => (
      <ark.div {...api.value.getOptionItemTextProps(optionItemProps)} {...attrs}>
        {slots.default?.()}
      </ark.div>
    )
  },
  {
    name: 'MenuOptionItemText',
  },
)
