// packages/solid/src/components/listbox/listbox-empty.tsx
import { createMemo, Show, splitProps } from 'solid-js'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory.tsx'
import { listboxAnatomy } from './listbox.anatomy.ts'
import { useListboxContext } from './use-listbox-context.ts'

const parts = listboxAnatomy.build()

export interface ListboxEmptyBaseProps extends PolymorphicProps<'div'> {}
export interface ListboxEmptyProps extends HTMLProps<'div'>, ListboxEmptyBaseProps {}

export const ListboxEmpty = (props: ListboxEmptyProps) => {
  const [localProps, restProps] = splitProps(props, ['children'])
  const listbox = useListboxContext()
  const isEmpty = createMemo(() => listbox().collection.size === 0)

  // the element stays mounted so the live region is already known to screen
  // readers when the message appears; only the children are conditional
  return (
    <ark.div {...parts.empty.attrs('')} role="status" aria-live="polite" aria-atomic="true" {...restProps}>
      <Show when={isEmpty()}>{localProps.children}</Show>
    </ark.div>
  )
}

// packages/svelte/src/lib/components/listbox/listbox-empty.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface ListboxEmptyBaseProps extends PolymorphicProps<'div'>, RefAttribute {}
  export interface ListboxEmptyProps extends Assign<HTMLProps<'div'>, ListboxEmptyBaseProps> {}
</script>

<script lang="ts">
  import { Ark } from '../factory/index.ts'
  import { listboxAnatomy } from './listbox.anatomy.ts'
  import { useListboxContext } from './use-listbox-context.ts'

  const parts = listboxAnatomy.build()

  let { ref = $bindable(null), children, ...restProps }: ListboxEmptyProps = $props()

  const listbox = useListboxContext()
  const isEmpty = $derived(listbox().collection.size === 0)
</script>

<!-- stays mounted so the live region is already known to screen readers when the
     message appears; only the children are conditional -->
<Ark as="div" bind:ref {...parts.empty.attrs('')} role="status" aria-live="polite" aria-atomic="true" {...restProps}>
  {#if isEmpty}{@render children?.()}{/if}
</Ark>
