// packages/solid/src/components/listbox/listbox-label.tsx
import { mergeProps } from '@zag-js/solid'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory'
import { useListboxContext } from './use-listbox-context'

export interface ListboxLabelBaseProps extends PolymorphicProps<'label'> {}
export interface ListboxLabelProps extends HTMLProps<'label'>, ListboxLabelBaseProps {}

export const ListboxLabel = (props: ListboxLabelProps) => {
  const listbox = useListboxContext()
  const mergedProps = mergeProps(() => listbox().getLabelProps(), props)

  return <ark.label {...mergedProps} />
}

// packages/svelte/src/lib/components/listbox/listbox-label.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types.js'

  export interface ListboxLabelBaseProps extends PolymorphicProps<'label'> {}
  export interface ListboxLabelProps extends Assign<HTMLProps<'label'>, ListboxLabelBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Ark } from '../factory/index.js'
  import { useListboxContext } from './use-listbox-context.js'

  const props: ListboxLabelProps = $props()

  const listbox = useListboxContext()
  const mergedProps = $derived(mergeProps(listbox().getLabelProps(), props))
</script>

<Ark as="label" {...mergedProps} />
