// packages/vue/src/switch/switch-input.tsx
import { defineComponent } from 'vue'
import { ark, type HTMLArkProps } from '../factory'
import type { ComponentWithProps } from '../utils'
import { useSwitchContext } from './switch-context'

export type SwitchInputProps = HTMLArkProps<'input'>

export const SwitchInput: ComponentWithProps<SwitchInputProps> = defineComponent({
  name: 'SwitchInput',
  setup(_, { attrs }) {
    const api = useSwitchContext()

    return () => <ark.input {...api.value.inputProps} {...attrs} />
  },
})

// packages/react/src/switch/switch-input.tsx
import { mergeProps } from '@zag-js/react'
import { ark, type HTMLArkProps } from '../factory'
import { forwardRef } from '../forward-ref'
import { useSwitchContext } from './switch-context'

export type SwitchInputProps = HTMLArkProps<'input'>

export const SwitchInput = forwardRef<'input'>((props, ref) => {
  const { inputProps } = useSwitchContext()
  const mergedProps = mergeProps(inputProps, props)

  return <ark.input {...mergedProps} ref={ref} />
})
