// packages/svelte/src/lib/components/field/examples/textarea-autoresize.svelte
<script lang="ts">
  import { Field } from '@ark-ui/svelte/field'
  import styles from 'styles/field.module.css'
</script>

<Field.Root class={styles.Root}>
  <Field.Label class={styles.Label}>Label</Field.Label>
  <Field.Textarea class={styles.Textarea} autoresize />
  <Field.HelperText class={styles.HelperText}>Some additional Info</Field.HelperText>
  <Field.ErrorText class={styles.ErrorText}>Error Info</Field.ErrorText>
</Field.Root>

// packages/solid/src/components/field/examples/textarea-autoresize.tsx
import { Field } from '@ark-ui/solid/field'

export const Textarea = () => {
  return (
    <Field.Root>
      <Field.Label>Label</Field.Label>
      <Field.Textarea autoresize />
      <Field.HelperText>Some additional Info</Field.HelperText>
      <Field.ErrorText>Error Info</Field.ErrorText>
    </Field.Root>
  )
}
