// packages/frameworks/react/src/clipboard/clipboard-indicator.tsx
import type { IndicatorProps } from '@zag-js/clipboard'
import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { createSplitProps } from '../create-split-props'
import { ark, type HTMLArkProps } from '../factory'
import type { Assign } from '../types'
import { useClipboardContext } from './clipboard-context'

export interface ClipboardIndicatorProps extends Assign<HTMLArkProps<'div'>, IndicatorProps> {}

export const ClipboardIndicator = forwardRef<HTMLDivElement, ClipboardIndicatorProps>(
  (props, ref) => {
    const [indicatorProps, localProps] = createSplitProps<IndicatorProps>()(props, ['copied'])
    const api = useClipboardContext()
    const mergedProps = mergeProps(api.getIndicatorProps(indicatorProps), localProps)

    return <ark.div {...mergedProps} ref={ref} />
  },
)

ClipboardIndicator.displayName = 'ClipboardIndicator'

// packages/frameworks/solid/src/clipboard/clipboard-indicator.tsx
import { mergeProps } from '@zag-js/solid'
import { Show, children, type JSX } from 'solid-js'
import { createSplitProps } from '../create-split-props'
import { ark, type HTMLArkProps } from '../factory'
import type { Assign } from '../types'
import { useClipboardContext } from './clipboard-context'

interface ElementProps {
  copied?: JSX.Element
}

export interface ClipboardIndicatorProps extends Assign<HTMLArkProps<'div'>, ElementProps> {}

export const ClipboardIndicator = (props: ClipboardIndicatorProps) => {
  const [indicatorProps, localProps] = createSplitProps<ElementProps>()(props, ['copied'])
  const api = useClipboardContext()
  const mergedProps = mergeProps(api().getIndicatorProps({ copied: api().isCopied }), localProps)
  const getChildren = children(() => localProps.children)

  return (
    <ark.div {...mergedProps}>
      <Show when={api().isCopied} fallback={getChildren()}>
        {indicatorProps.copied}
      </Show>
    </ark.div>
  )
}
