// packages/vue/src/components/date-input/date-input-control.vue
<script lang="ts">
import type { ControlState } from '@zag-js/date-input'
import type { HTMLAttributes } from 'vue'
import type { PolymorphicProps, PolymorphicSlots } from '../factory.ts'

export interface DateInputControlState extends ControlState {}
export interface DateInputControlBaseProps extends PolymorphicProps {}
export interface DateInputControlProps
  extends
    DateInputControlBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
</script>

<script setup lang="ts">
import { ark } from '../factory.ts'
import { useDateInputContext } from './use-date-input-context.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

defineProps<DateInputControlProps>()
defineSlots<PolymorphicSlots<DateInputControlState>>()
const dateInput = useDateInputContext()

useForwardExpose()
</script>

<template>
  <ark.div v-bind="dateInput.getControlProps()" :state="dateInput.getControlState()" :as-child="asChild">
    <template v-if="$slots.render" #render="scope">
      <slot name="render" v-bind="scope" />
    </template>
    <template v-else #default>
      <slot />
    </template>
  </ark.div>
</template>

// packages/react/src/components/date-input/date-input-control.tsx
'use client'

import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory.ts'
import { useDateInputContext } from './use-date-input-context.ts'
import type { ControlState } from '@zag-js/date-input'

export interface DateInputControlState extends ControlState {}

export interface DateInputControlBaseProps extends PolymorphicProps<DateInputControlState> {}
export interface DateInputControlProps extends HTMLProps<'div'>, DateInputControlBaseProps {}

export const DateInputControl = forwardRef<HTMLDivElement, DateInputControlProps>((props, ref) => {
  const dateInput = useDateInputContext()
  const mergedProps = mergeProps(dateInput.getControlProps(), props)

  return <ark.div {...mergedProps} ref={ref} state={dateInput.getControlState()} />
})

DateInputControl.displayName = 'DateInputControl'
