// packages/vue/src/components/time-picker/time-picker-clear-trigger.vue
<script lang="ts">
import type { ButtonHTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory'

export interface TimePickerClearTriggerBaseProps extends PolymorphicProps {}
export interface TimePickerClearTriggerProps
  extends TimePickerClearTriggerBaseProps,
    /**
     * @vue-ignore
     */
    ButtonHTMLAttributes {}
</script>

<script setup lang="ts">
import { ark } from '../factory'
import { useTimePickerContext } from './use-time-picker-context'

defineProps<TimePickerClearTriggerProps>()
const timePicker = useTimePickerContext()
</script>

<template>
  <ark.button v-bind="timePicker.getClearTriggerProps()" :as-child="asChild">
    <slot />
  </ark.button>
</template>

// packages/solid/src/components/time-picker/time-picker-clear-trigger.tsx
import { mergeProps } from '@zag-js/solid'
import type { Assign } from '../../types'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory'
import { useTimePickerContext } from './use-time-picker-context'

export interface TimePickerClearTriggerBaseProps extends PolymorphicProps<'button'> {}
export interface TimePickerClearTriggerProps
  extends Assign<HTMLProps<'button'>, TimePickerClearTriggerBaseProps> {}

export const TimePickerClearTrigger = (props: TimePickerClearTriggerProps) => {
  const timePicker = useTimePickerContext()
  const mergedProps = mergeProps(() => timePicker().getClearTriggerProps(), props)

  return <ark.button {...mergedProps} />
}
