// packages/vue/src/components/tour/tour-description.vue
<script lang="ts">
import type { HTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory.ts'

export interface TourDescriptionBaseProps extends PolymorphicProps {}
export interface TourDescriptionProps
  extends
    TourDescriptionBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
</script>

<script setup lang="ts">
import { ark } from '../factory.ts'
import { useTourContext } from './use-tour-context.ts'
import { useForwardExpose } from '../../utils/use-forward-expose.ts'

defineProps<TourDescriptionProps>()
const tour = useTourContext()
const slots = defineSlots<{
  default?(): unknown
}>()

useForwardExpose()
</script>

<template>
  <ark.div v-bind="tour.getDescriptionProps()" :as-child="asChild">
    <slot>{{ slots.default?.() || tour.step?.description }}</slot>
  </ark.div>
</template>

// packages/solid/src/components/tour/tour-description.tsx
import { mergeProps } from "@zag-js/solid";
import { type HTMLProps, type PolymorphicProps, ark } from "../factory";
import { useTourContext } from "./use-tour-context";

export interface TourDescriptionBaseProps extends PolymorphicProps<"div"> {}
export interface TourDescriptionProps
	extends HTMLProps<"div">,
		TourDescriptionBaseProps {}

export const TourDescription = (props: TourDescriptionProps) => {
	const tour = useTourContext();
	const mergedProps = mergeProps(() => tour().getDescriptionProps(), props);

	return (
		<ark.div {...mergedProps}>
			{mergedProps.children || tour().step?.description}
		</ark.div>
	);
};
