// packages/frameworks/solid/src/slider/slider-output.tsx
import { mergeProps } from '@zag-js/solid'
import { type JSX } from 'solid-js'
import { ark, type HTMLArkProps } from '../factory'
import { runIfFn } from '../run-if-fn'
import type { Assign } from '../types'
import { useSliderContext } from './slider-context'
import { type UseSliderReturn } from './use-slider'

export type SliderOutputProps = Assign<
  HTMLArkProps<'output'>,
  {
    children?: ((pages: UseSliderReturn) => JSX.Element) | JSX.Element
  }
>

export const SliderOutput = (props: SliderOutputProps) => {
  const slider = useSliderContext()

  const getChildren = () => runIfFn(props.children, slider)
  const outputProps = mergeProps(() => slider().outputProps, props)

  return <ark.output {...outputProps}>{getChildren()}</ark.output>
}

// packages/frameworks/react/src/slider/slider-output.tsx
import { mergeProps } from '@zag-js/react'
import { forwardRef, type ReactNode } from 'react'
import { ark, type HTMLArkProps } from '../factory'
import { runIfFn } from '../run-if-fn'
import { type Assign } from '../types'
import { useSliderContext } from './slider-context'
import { type UseSliderReturn } from './use-slider'

export interface SliderOutputProps
  extends Assign<
    HTMLArkProps<'output'>,
    { children?: ((api: UseSliderReturn) => ReactNode) | ReactNode }
  > {}

export const SliderOutput = forwardRef<HTMLOutputElement, SliderOutputProps>((props, ref) => {
  const { children, ...rest } = props
  const api = useSliderContext()
  const mergedProps = mergeProps(api.outputProps, rest)

  const view = runIfFn(children, api)

  return (
    <ark.output {...mergedProps} ref={ref}>
      {view}
    </ark.output>
  )
})

SliderOutput.displayName = 'SliderOutput'
