// packages/solid/src/components/format/format-number.tsx
import { formatNumber } from '@zag-js/i18n-utils'
import { createMemo } from 'solid-js'
import { useLocaleContext } from '../../providers'

export interface FormatNumberProps extends Intl.NumberFormatOptions {
  /**
   * The number to format
   */
  value: number
}

export const FormatNumber = (props: FormatNumberProps) => {
  const ctx = useLocaleContext()
  const text = createMemo(() => {
    const { value, ...intlOptions } = props
    return formatNumber(value, ctx().locale, intlOptions)
  })

  return <>{text()}</>
}

// packages/react/src/components/format/format-number.tsx
import { formatNumber } from '@zag-js/i18n-utils'
import { useMemo } from 'react'
import { useLocaleContext } from '../../providers/locale'

export interface FormatNumberProps extends Intl.NumberFormatOptions {
  /**
   * The number to format
   */
  value: number
}

export const FormatNumber = (props: FormatNumberProps) => {
  const { locale } = useLocaleContext()

  const text = useMemo(() => {
    const { value, ...intlOptions } = props
    return formatNumber(value, locale, intlOptions)
  }, [props, locale])

  return <>{text}</>
}

FormatNumber.displayName = 'FormatNumber'
