// packages/solid/src/components/signature-pad/signature-pad-root-provider.tsx
import { mergeProps } from '@zag-js/solid'
import { createSplitProps } from '../../utils/create-split-props'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory'
import type { UseSignaturePadReturn } from './use-signature-pad'
import { SignaturePadProvider } from './use-signature-pad-context'

interface RootProviderProps {
  value: UseSignaturePadReturn
}

export interface SignaturePadRootProviderBaseProps extends PolymorphicProps<'div'> {}
export interface SignaturePadRootProviderProps
  extends HTMLProps<'div'>,
    RootProviderProps,
    SignaturePadRootProviderBaseProps {}

export const SignaturePadRootProvider = (props: SignaturePadRootProviderProps) => {
  const [{ value: signaturePad }, localProps] = createSplitProps<RootProviderProps>()(props, ['value'])
  const mergedProps = mergeProps(() => signaturePad().getRootProps(), localProps)

  return (
    <SignaturePadProvider value={signaturePad}>
      <ark.div {...mergedProps} />
    </SignaturePadProvider>
  )
}

// packages/svelte/src/lib/components/signature-pad/signature-pad-root-provider.svelte
<script module lang="ts">
  import type { Assign, HTMLProps, PolymorphicProps } from '$lib/types'
  import type { UseSignaturePadReturn } from './use-signature-pad.svelte'

  export interface SignaturePadRootProviderBaseProps extends PolymorphicProps<'div'> {
    value: UseSignaturePadReturn
  }
  export interface SignaturePadRootProviderProps extends Assign<HTMLProps<'div'>, SignaturePadRootProviderBaseProps> {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Ark } from '../factory'
  import { SignaturePadProvider } from './use-signature-pad-context'

  let { value, ...props }: SignaturePadRootProviderProps = $props()

  const mergedProps = $derived(mergeProps(value().getRootProps(), props))

  SignaturePadProvider(value)
</script>

<Ark as="div" {...mergedProps} />
