// packages/solid/src/components/timer/timer-item.tsx
import { mergeProps } from '@zag-js/solid'
import type { ItemProps } from '@zag-js/timer'
import { createSplitProps } from '../../utils/create-split-props'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory'
import { useTimerContext } from './use-timer-context'

export interface TimerItemBaseProps extends ItemProps, PolymorphicProps<'div'> {}
export interface TimerItemProps extends HTMLProps<'div'>, TimerItemBaseProps {}

export const TimerItem = (props: TimerItemProps) => {
  const [itemProps, localProps] = createSplitProps<ItemProps>()(props, ['type'])
  const timer = useTimerContext()

  const mergedProps = mergeProps(() => timer().getItemProps(itemProps), localProps)

  return <ark.div {...mergedProps}>{timer().formattedTime[itemProps.type]}</ark.div>
}

// packages/vue/src/components/timer/timer-item.vue
<script lang="ts">
import type { ItemProps } from '@zag-js/timer'
import type { HTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory'

export interface TimerItemBaseProps extends ItemProps, PolymorphicProps {}
export interface TimerItemProps
  extends TimerItemBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
</script>

<script setup lang="ts">
import { ark } from '../factory'
import { useTimerContext } from './use-timer-context'
import { useForwardExpose } from '../../utils'

const props = defineProps<TimerItemProps>()
const timer = useTimerContext()

useForwardExpose()
</script>

<template>
  <ark.div v-bind="timer.getItemProps(props)" :as-child="asChild">
    {{ timer.formattedTime[props.type] }}
  </ark.div>
</template>
