// packages/svelte/src/lib/components/number-input/number-input-context.svelte
<script module lang="ts">
  import type { Snippet } from 'svelte'
  import type { UseNumberInputContext } from './use-number-input-context'

  export interface NumberInputContextProps {
    render: Snippet<[UseNumberInputContext]>
  }
</script>

<script lang="ts">
  import { useNumberInputContext } from './use-number-input-context'

  const { render }: NumberInputContextProps = $props()

  const context = useNumberInputContext()
</script>

{@render render(context)}

// packages/frameworks/react/src/number-input/number-input-context.tsx
import type { ReactNode } from 'react'
import { useNumberInputContext, type UseNumberInputContext } from './use-number-input-context'

export interface NumberInputContextProps {
  children: (context: UseNumberInputContext) => ReactNode
}

export const NumberInputContext = (props: NumberInputContextProps) =>
  props.children(useNumberInputContext())
