// packages/vue/src/select/select-option-group-label.tsx
import { defineComponent, PropType } from 'vue'
import { ark, HTMLArkProps } from '../factory'
import { ComponentWithProps, getValidChildren } from '../utils'
import { useSelectContext } from './select-context'

export interface SelectOptionGroupLabelProps extends HTMLArkProps<'label'> {
  htmlFor: string
}

export const SelectOptionGroupLabel: ComponentWithProps<SelectOptionGroupLabelProps> =
  defineComponent({
    props: {
      htmlFor: String as PropType<SelectOptionGroupLabelProps['htmlFor']>,
    },
    setup(props, { slots, attrs }) {
      const api = useSelectContext()

      return () => (
        <ark.label
          {...api.value.getOptionGroupLabelProps({ htmlFor: props.htmlFor as string })}
          {...attrs}
        >
          {() => getValidChildren(slots)}
        </ark.label>
      )
    },
  })

// packages/solid/src/select/select-option-group-label.tsx
import type { Assign } from '@polymorphic-factory/solid'
import { createSplitProps } from '../create-split-props'
import { ark, HTMLArkProps } from '../factory'
import { useSelectContext } from './select-context'

type OptionGroupLabelProps = { htmlFor: string }
export type SelectOptionGroupLabelProps = Assign<HTMLArkProps<'label'>, OptionGroupLabelProps>

export const SelectOptionGroupLabel = (props: SelectOptionGroupLabelProps) => {
  const [optionProps, labelProps] = createSplitProps<OptionGroupLabelProps>()(props, ['htmlFor'])
  const select = useSelectContext()

  return <ark.label {...select().getOptionGroupLabelProps(optionProps)} {...labelProps} />
}
