// packages/react/src/components/carousel/carousel-viewport.tsx
import { mergeProps } from '@zag-js/react'
import { type HTMLAttributes, forwardRef } from 'react'
import { type PolymorphicProps, ark } from '../factory'
import { useCarouselContext } from './use-carousel-context'

export interface CarouselViewportBaseProps extends PolymorphicProps {}
export interface CarouselViewportProps
  extends HTMLAttributes<HTMLDivElement>,
    CarouselViewportBaseProps {}

export const CarouselViewport = forwardRef<HTMLDivElement, CarouselViewportProps>((props, ref) => {
  const carousel = useCarouselContext()
  const mergedProps = mergeProps(carousel.getViewportProps(), props)

  return <ark.div {...mergedProps} ref={ref} />
})

CarouselViewport.displayName = 'CarouselViewport'

// packages/vue/src/components/carousel/carousel-viewport.vue
<script lang="ts">
import type { HTMLAttributes } from 'vue'
import type { PolymorphicProps } from '../factory'

export interface CarouselViewportBaseProps extends PolymorphicProps {}
export interface CarouselViewportProps
  extends CarouselViewportBaseProps,
    /**
     * @vue-ignore
     */
    HTMLAttributes {}
</script>

<script setup lang="ts">
import { ark } from '../factory'
import { useCarouselContext } from './use-carousel-context'

defineProps<CarouselViewportProps>()
const carousel = useCarouselContext()
</script>

<template>
  <ark.div v-bind="carousel.getViewportProps()" :as-child="asChild">
    <slot />
  </ark.div>
</template>
