// packages/frameworks/vue/src/byte-format/byte-format.tsx
import { formatBytes } from '@zag-js/file-utils'
import { computed, defineComponent } from 'vue'
import { useLocaleContext } from '../locale'
import { LOCALE_DEFAULT } from '../locale/locale-context'

export interface ByteFormatProps {
  /**
   * The unit granularity to display
   */
  unit?: 'bit' | 'byte'
  /**
   * The unit display
   */
  unitDisplay?: 'long' | 'short' | 'narrow'
  /**
   * The byte size to format
   */
  value: number
}

export const ByteFormat = defineComponent<ByteFormatProps>(
  (props) => {
    const ctx = useLocaleContext(LOCALE_DEFAULT)
    const text = computed(() => {
      const { value, ...intlProps } = props
      return formatBytes(value, ctx.value.locale, intlProps)
    })
    return () => text.value
  },
  {
    name: 'ByteFormat',
    props: ['unit', 'unitDisplay', 'value'],
  },
)

// packages/frameworks/solid/src/byte-format/byte-format.tsx
import { formatBytes } from '@zag-js/file-utils'
import { createMemo, splitProps } from 'solid-js'
import { useLocaleContext } from '../locale'

export interface ByteFormatProps {
  /**
   * The unit granularity to display
   */
  unit?: 'bit' | 'byte'
  /**
   * The unit display
   */
  unitDisplay?: 'long' | 'short' | 'narrow'
  /**
   * The byte size to format
   */
  value: number
}

export const ByteFormat = (props: ByteFormatProps) => {
  const [valueProps, intlProps] = splitProps(props, ['value'])
  const ctx = useLocaleContext()
  const text = createMemo(() => formatBytes(valueProps.value, ctx().locale, intlProps))
  return <>{text}</>
}

ByteFormat.displayName = 'ByteFormat'
