// packages/svelte/src/lib/components/avatar/avatar-fallback.svelte
<script module lang="ts">
  import type { HTMLProps, PolymorphicProps } from '$lib/types'

  export interface AvatarFallbackBaseProps extends PolymorphicProps<'span'> {}
  export interface AvatarFallbackProps extends HTMLProps<'span'>, AvatarFallbackBaseProps {}
</script>

<script lang="ts">
  import { useAvatarContext } from './use-avatar-context'
  import { mergeProps } from '@zag-js/svelte'
  import Ark from '../ark.svelte'

  const props: AvatarFallbackProps = $props()

  const avatar = useAvatarContext()
  const mergedProps = $derived(mergeProps(avatar().getFallbackProps(), props))
</script>

<Ark as="span" {...mergedProps} />

// packages/solid/src/components/avatar/avatar-fallback.tsx
import { mergeProps } from '@zag-js/solid'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory'
import { useAvatarContext } from './use-avatar-context'

export interface AvatarFallbackBaseProps extends PolymorphicProps<'span'> {}
export interface AvatarFallbackProps extends HTMLProps<'span'>, AvatarFallbackBaseProps {}

export const AvatarFallback = (props: AvatarFallbackProps) => {
  const context = useAvatarContext()
  const mergedProps = mergeProps(() => context().getFallbackProps(), props)
  return <ark.span {...mergedProps} />
}
