// packages/solid/src/range-slider/range-slider-label.tsx
import { ark, type HTMLArkProps } from '../factory'
import { useRangeSliderContext } from './range-slider-context'

export type RangeSliderLabelProps = HTMLArkProps<'label'>

export const RangeSliderLabel = (props: RangeSliderLabelProps) => {
  const slider = useRangeSliderContext()

  return <ark.label {...slider().labelProps} {...props} />
}

// packages/vue/src/range-slider/range-slider-label.tsx
import { defineComponent } from 'vue'
import { ark, HTMLArkProps } from '../factory'
import { ComponentWithProps, getValidChildren } from '../utils'
import { useRangeSliderContext } from './range-slider-context'

export type RangeSliderLabelProps = HTMLArkProps<'label'>

export const RangeSliderLabel: ComponentWithProps<RangeSliderLabelProps> = defineComponent({
  name: 'RangeSliderLabel',
  setup(_, { slots, attrs }) {
    const api = useRangeSliderContext()

    return () => (
      <ark.label {...api.value.labelProps} {...attrs}>
        {() => getValidChildren(slots)}
      </ark.label>
    )
  },
})
