// packages/react/src/components/accordion/examples/context.tsx
import { Accordion } from '@ark-ui/react/accordion'
import { ChevronDownIcon } from 'lucide-react'
import styles from 'styles/accordion.module.css'

export const Context = () => {
  return (
    <Accordion.Root className={styles.Root} defaultValue={['ark-ui']}>
      <Accordion.Context>
        {(context) => (
          <output>
            <div>context.value: {JSON.stringify(context.value)}</div>
            <div>context.focusedValue: {context.focusedValue || 'null'}</div>
          </output>
        )}
      </Accordion.Context>

      {items.map((item) => (
        <Accordion.Item className={styles.Item} key={item.value} value={item.value}>
          <Accordion.ItemTrigger className={styles.ItemTrigger}>
            {item.title}
            <Accordion.ItemIndicator className={styles.ItemIndicator}>
              <ChevronDownIcon />
            </Accordion.ItemIndicator>
          </Accordion.ItemTrigger>
          <Accordion.ItemContent className={styles.ItemContent}>
            <div className={styles.ItemBody}>{item.content}</div>
          </Accordion.ItemContent>
        </Accordion.Item>
      ))}
    </Accordion.Root>
  )
}

const items = [
  {
    value: 'ark-ui',
    title: 'What is Ark UI?',
    content: 'A headless component library for building accessible web apps.',
  },
  {
    value: 'getting-started',
    title: 'How to get started?',
    content: 'Install the package and import the components you need.',
  },
  {
    value: 'maintainers',
    title: 'Who maintains this project?',
    content: 'Ark UI is maintained by the Chakra UI team.',
  },
]

// packages/angular/src/accordion/examples/context.ts
import { JsonPipe } from '@angular/common'
import { ChangeDetectionStrategy, Component } from '@angular/core'
import {
  ArkAccordionContext,
  ArkAccordionItem,
  ArkAccordionItemContent,
  ArkAccordionItemIndicator,
  ArkAccordionItemTrigger,
  ArkAccordionRoot,
} from '@ark-ui/angular/accordion'
import { accordionExampleStyles } from '../accordion-example-styles'
import { AccordionChevronDownIcon } from './icons'

@Component({
  selector: 'accordion-context-example',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    ArkAccordionRoot,
    ArkAccordionContext,
    ArkAccordionItem,
    ArkAccordionItemTrigger,
    ArkAccordionItemContent,
    ArkAccordionItemIndicator,
    AccordionChevronDownIcon,
    JsonPipe,
  ],
  template: `
    <div arkAccordion [defaultValue]="['ark-ui']">
      <ng-container *arkAccordionContext="let accordion">
        <output>
          <div>context.value: {{ accordion().value | json }}</div>
          <div>context.focusedValue: {{ accordion().focusedValue || 'null' }}</div>
        </output>
      </ng-container>

      @for (item of items; track item.value) {
        <div arkAccordionItem [value]="item.value">
          <button type="button" arkAccordionItemTrigger>
            {{ item.title }}
            <span arkAccordionItemIndicator><accordion-chevron-down-icon /></span>
          </button>
          <div arkAccordionItemContent>
            <div class="item-body">{{ item.content }}</div>
          </div>
        </div>
      }
    </div>
  `,
  styles: [accordionExampleStyles],
})
export class AccordionContextExample {
  readonly items = accordionItems
}

const accordionItems = [
  {
    value: 'ark-ui',
    title: 'What is Ark UI?',
    content: 'A headless component library for building accessible web apps.',
  },
  {
    value: 'getting-started',
    title: 'How to get started?',
    content: 'Install the package and import the components you need.',
  },
  {
    value: 'maintainers',
    title: 'Who maintains this project?',
    content: 'Ark UI is maintained by the Chakra UI team.',
  },
]
