// packages/react/src/components/tags-input/use-tags-input-item-context.ts
'use client'

import type { ItemState } from '@zag-js/tags-input'
import { createContext } from '../../utils/create-context.ts'

export interface UseTagsInputItemContext extends ItemState {}

export const [TagsInputItemProvider, useTagsInputItemContext] = createContext<UseTagsInputItemContext>({
  name: 'TagsInputItemContext',
  hookName: 'useTagsInputItemContext',
  providerName: '<TagsInputItemProvider />',
})

// packages/solid/src/components/tags-input/use-tags-input-item-context.ts
import type { ItemState } from '@zag-js/tags-input'
import type { Accessor } from 'solid-js'
import { createContext } from '../../utils/create-context.ts'

export interface UseTagsInputItemContext extends Accessor<ItemState> {}

export const [TagsInputItemProvider, useTagsInputItemContext] = createContext<UseTagsInputItemContext>({
  hookName: 'useTagsInputItemContext',
  providerName: '<TagsInputItemProvider />',
})
